### PR TITLE
Resolve lvalues after parameterization

### LINKED ISSUE #4130: Lvalues not recognized properly in classes deriving from their own parameters
Minimal reproduction example:
```SystemVerilog
class Foo;
endclass

class Bar #(type BASE=Foo) extends BASE;
  task body();
    int v = 0;
    v = 1;
  endtask
endclass
```

Ran with 
```
$ verilator --lint-only bad.v --debug
```
Result:
```
%Error: Internal Error: bad.v:7:7: ../V3Broken.cpp:225: Assignment LHS is not an lvalue
-node: ASSIGN 0x555556476f30 <e627> {d7ah} @dt=0x5555564768d0@(G/sw32)
    7 |     v = 1;
      |       ^
                        ... See the manual at https://verilator.org/verilator_doc.html for more assistance.
```

Verilator version: a10b51705f8ed2634608097f8be1be96c4a1532b
OS: Gentoo Linux (x86_64)

### PR DESCRIPTION
**Pull request by kboronski-ant**
Fixes #4130

Some variable references stay as ParseRefs until classes get properly parametrized. After they become VerRefs `LinkLValueVisitor` will be able to set lvalues appropriately.

### CODE REVIEW

**Review by wsnyder — COMMENTED** [review]
I don't see any side effects to calling V3LinkLValue twice like this.  Feel free to merge when you're done (I see it's a draft).

File: src/Verilator.cpp [hunk 1]
```diff
@@ -133,8 +133,6 @@ static void process() {
     v3Global.opt.checkParameters();
     // Correct state we couldn't know at parse time, repair SEL's
     V3LinkResolve::linkResolve(v3Global.rootp());
-    // Set Lvalue's in variable refs
-    V3LinkLValue::linkLValue(v3Global.rootp());
```
Comment (wsnyder) [inline src/Verilator.cpp:137]: V3Simulate, used by parameterification seems to care about the settings, so I think this is still needed.

Comment (kboronski-ant) [reply src/Verilator.cpp:137]: I suppose that you are talking about using the simulation node under V3Const, which is used to constify parameters, right?

From what I've seen, the only place so far in which lvalueness it seems to matter is some code in visitor override for `AstVarRef` in `SimulateVisitor`. I wonder if this is something that can be worked around.

I'll revert that change for now as I don't know if it's safe to skip this stage.

Do you have any ideas what kind of scenario could break it, given that all tests pass?
