### PR TITLE
Fix #3511: Nested default assignment for struct pattern

### LINKED ISSUE #3511: Use of the default keyword applies to members in nested structures not working as expected
The issue was encountered when I was working on fixing [Support pattern member assignment with data type #2328](https://github.com/verilator/verilator/issues/2328 ) and created this sample Test Case from IEEE 1800-2017 SV CH:10.9.2

The standard mentioned that "Use of the default keyword applies to members in nested structures or elements in unpacked arrays in
structures" but this is not the case as below

**Example:**
```
module top();
/* verilator lint_off UNPACKED */

  struct { // IEEE 1800-2017 SV CH:10.9.2
    int A;
    struct {
    int B, C;
    } BC1, BC2;
  } ABC, DEF;

  
  initial begin;

  DEF = '{default:10}; 
  $display("DEF.A=%d, DEF.BC1.B=%d, DEF.BC1.C=%d, DEF.BC2.B=%d, DEF.BC2.C=%d", DEF.A, DEF.BC1.B, DEF.BC1.C, DEF.BC2.B, DEF.BC2.C);

  $finish;
  end

endmodule
```

**Output:**

`DEF.A=         10, DEF.BC1.B=          0, DEF.BC1.C=         10, DEF.BC2.B=          0, DEF.BC2.C=         10`

**Error:**
_Value of 10 is not applied to DEF.BC1.B and DEF.BC2.B
They are assigned 0_

**Version:**
_git master:_ _Verilator 4.225 devel rev v4.224-49-ge0b61cea_

**Notes:**

Any information on what might be happening would be much appreciated

### PR DESCRIPTION
**Pull request by MG525**
Fix #3511

1. The new implementation guarantees default assignment using "default" or "type_default" in nested struct
2. Some refactoring has been done to reuse the code in different phases
3. Recursion is used when struct member is hit as a member and not yet matched
4. Modified the test case to hit the new implementation
5. Removed legacy comment in bison parser

### CODE REVIEW

File: src/V3Width.cpp [hunk 1]
```diff
@@ -3626,44 +3626,23 @@ class WidthVisitor final : public VNVisitor {
...
-                    patp = it2->second;
-                    newpatp = patp->cloneTree(false);
-                    patp = newpatp;
-                } else if (defaultp) {
-                    // default_value for any unassigned member yet
-                    newpatp = defaultp->cloneTree(false);
-                    patp = newpatp;
+                // default or deafult_type assignment
+                if (AstNodeUOrStructDType* memp_nested_vdtypep
+                    = VN_CAST(memp->virtRefDTypep(), NodeUOrStructDType)) {
```
Comment (wsnyder) [inline src/V3Width.cpp:3633]:
```suggestion
                if (AstNodeUOrStructDType* const memp_nested_vdtypep
                    = VN_CAST(memp->virtRefDTypep(), NodeUOrStructDType)) {
```

File: src/V3Width.cpp [hunk 2]
```diff
@@ -3672,6 +3651,66 @@ class WidthVisitor final : public VNVisitor {
         }
         VL_DO_DANGLING(pushDeletep(nodep), nodep);  // Deletes defaultp also, if present
     }
+
+    AstNode*
+    nestedvalueConcat_patternUOrStruct(AstNodeUOrStructDType* memp_vdtypep, AstPatMember* defaultp,
+                                       AstNode* newp, AstPattern* nodep,
+                                       std::map<const std::string, AstPatMember*> dtypemap) {
```
Comment (wsnyder) [inline src/V3Width.cpp:3658]: Add a "using" typedef at the top of the class for this std::map, since use it multiple places.

File: src/V3Width.cpp [hunk 3]
```diff
@@ -3672,6 +3651,66 @@ class WidthVisitor final : public VNVisitor {
...
+        AstPatMember* patp = nullptr;
+        for (AstMemberDType* memp_nested = memp_vdtypep->membersp(); memp_nested;
+             memp_nested = VN_AS(memp_nested->nextp(), MemberDType)) {
+            if (AstNodeUOrStructDType* memp_multinested_vdtypep
```
Comment (wsnyder) [inline src/V3Width.cpp:3662]:
```suggestion
            if (AstNodeUOrStructDType* const memp_multinested_vdtypep
```

File: src/V3Width.cpp [hunk 4]
```diff
@@ -3672,6 +3651,66 @@ class WidthVisitor final : public VNVisitor {
...
+            // default_value for data_type
+            patp = it->second->cloneTree(false);
+        } else if (defaultp) {
+            // default_value for any unmatched member yet
+            patp = defaultp->cloneTree(false);
+        } else {
+            if (!VN_IS(memp_vdtypep, UnionDType)) {
+                nodep->v3error("Assignment pattern missed initializing elements: "
+                               << memp->virtRefDTypep()->prettyDTypeName() << " "
+                               << memp->prettyName());
```
Comment (wsnyder) [inline src/V3Width.cpp:3691]:
```suggestion
                               << memp->virtRefDTypep()->prettyDTypeNameQ() << " "
                               << memp->prettyNameQ());
```

File: src/V3Width.cpp [hunk 5]
```diff
@@ -3672,6 +3651,66 @@ class WidthVisitor final : public VNVisitor {
...
+
+    AstNode* valueConcat_patternUOrStruct(AstPatMember* patp, AstNode* newp, AstMemberDType* memp,
+                                          AstPattern* nodep) {
+        if (patp) {
+            patp->dtypep(memp);
+            AstNode* const valuep = patternMemberValueIterate(patp);
+            if (!newp) {
+                newp = valuep;
+            } else {
+                AstConcat* const concatp = new AstConcat(patp->fileline(), newp, valuep);
```
Comment (wsnyder) [inline src/V3Width.cpp:3705]:
```suggestion
                AstConcat* const concatp = new AstConcat{patp->fileline(), newp, valuep};
```

**Review by wsnyder — COMMENTED** [review]
Looks good, thanks, just some minor cleanups below.

File: src/V3Width.cpp [hunk 6]
```diff
@@ -3672,6 +3650,65 @@ class WidthVisitor final : public VNVisitor {
...
+
+    AstNode* nestedvalueConcat_patternUOrStruct(AstNodeUOrStructDType* memp_vdtypep,
+                                                AstPatMember* defaultp, AstNode* newp,
+                                                AstPattern* nodep, DTypeMap dtypemap) {
+        AstPatMember* patp = nullptr;
+        for (AstMemberDType* memp_nested = memp_vdtypep->membersp(); memp_nested;
+             memp_nested = VN_AS(memp_nested->nextp(), MemberDType)) {
+            if (AstNodeUOrStructDType* const memp_multinested_vdtypep
+                = VN_CAST(memp_nested->virtRefDTypep(), NodeUOrStructDType)) {
+                newp = nestedvalueConcat_patternUOrStruct(memp_multinested_vdtypep, defaultp, newp,
```
Comment (wsnyder) [inline src/V3Width.cpp:3662]:
```suggestion
                = VN_CAST(memp_nested->virtRefDTypep(), NodeUOrStructDType)) {
                // When unpacked struct/union is supported this if will need some additional conditions
                newp = nestedvalueConcat_patternUOrStruct(memp_multinested_vdtypep, defaultp, newp,
```
