### PR TITLE
Fix Windows filename format, etc. (#3873)

### LINKED ISSUE #3873: Support windows backslash paths
Thanks for taking the time to report this.

I'm getting xmake to support verilator, https://github.com/xmake-io/xmake/issues/3257#issuecomment-1382728743

I've got it working successfully on macos/linux, but I'm having some problems on windows, but I don't know what's causing the problem.

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

main.v

```
module hello;
  initial begin
    $display("hello world!");
    $finish ;
  end
endmodule
```

```console
verilator --cc --make cmake --prefix test --Mdir C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_A1905FCCCD594F708649E5D19828E0C0.dir C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_A1905FCCCD594F708649E5D19828E0C0.dir\main.v

%Error: Cannot find file containing module: C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v
%Error: This may be because there's no search path specified with -I<dir>.
        ... Looked in:
             C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v
             C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v.v
             C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v.sv
             C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir/C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v
             C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir/C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v.v
             C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir/C:\Users\ruki\AppData\Local\Temp\.xmake\230114\_B16190110D014270819F09DD1F59C8C0.dir\main.v.sv
%Error: Exiting due to 2 error(s)

```

What 'verilator --version' are you using?  Did you try it with the git master version?

 rev v5.004-58-g5fce23e90 (mod)

What OS and distribution are you using?

Windows 7

May we assist you in trying to fix this in Verilator yourself?

sure

### PR DESCRIPTION
**Pull request by donlon**
Just combined some similar changes into a single PR to make things easier

Path processing functions now support back slash, and some compiler warnings on MSVC are fixed

It seems that this also fixes #3873.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -41,3 +41,5 @@ verilator-config-version.cmake
 **/_build/*
 **/obj_dir/*
 /.vscode/
+/.idea/
+/cmake-build-*/
```
Comment (donlon) [inline .gitignore:45]: These are the project path and default CMake build output path for CLion, a popular C/C++ IDE

File: src/V3Table.cpp [hunk 2]
```diff
@@ -181,7 +181,7 @@ class TableVisitor final : public VNVisitor {
             // We'll make the table with a separate natural alignment for each output var, so
             // always have 8, 16 or 32 bit widths, so use widthTotalBytes
             m_outWidthBytes += nodep->varp()->dtypeSkipRefp()->widthTotalBytes();
-            m_outVarps.emplace_back(vscp, m_outVarps.size());
+            m_outVarps.emplace_back(vscp, (unsigned)m_outVarps.size());
```
Comment (wsnyder) [inline src/V3Table.cpp:184]:
```suggestion
            m_outVarps.emplace_back(vscp, static_cast<unsigned>(m_outVarps.size()));
```

File: src/V3Os.cpp [hunk 3]
```diff
@@ -133,22 +135,26 @@ string V3Os::filenameFromDirBase(const string& dir, const string& basename) {
...
 
-string V3Os::filenameDir(const string& filename) {
-    string::size_type pos;
-    if ((pos = filename.rfind('/')) != string::npos) {
-        return filename.substr(0, pos);
-    } else {
+string V3Os::filenameDir(const string& filename) VL_PURE {
+    // std::filesystem::path::parent_path
+    auto it = filename.rbegin();
+    for (; it != filename.rend(); it++) {
```
Comment (wsnyder) [inline src/V3Os.cpp:141]:
```suggestion
    for (; it != filename.rend(); ++it) {
```

File: src/V3Os.cpp [hunk 4]
```diff
@@ -133,22 +135,26 @@ string V3Os::filenameFromDirBase(const string& dir, const string& basename) {
...
 
 string V3Os::filenameNonDir(const string& filename) VL_PURE {
-    string::size_type pos;
-    if ((pos = filename.rfind('/')) != string::npos) {
-        return filename.substr(pos + 1);
-    } else {
-        return filename;
+    // std::filesystem::path::filename
+    auto it = filename.rbegin();
+    for (; it != filename.rend(); it++) {
```
Comment (wsnyder) [inline src/V3Os.cpp:154]:
```suggestion
    for (; it != filename.rend(); ++it) {
```

File: src/V3Os.cpp [hunk 5]
```diff
@@ -133,22 +135,26 @@ string V3Os::filenameFromDirBase(const string& dir, const string& basename) {
...
+        if (isSlash(*it)) break;
     }
+    return {it.base(), filename.end()};
```
Comment (wsnyder) [inline src/V3Os.cpp:157]:
```suggestion
    return string{it.base(), filename.end()};
```

**Review by wsnyder — COMMENTED** [review]
Great improvements!  Just some minor comments.
