### PR TITLE
Fix multiple edge timing controls in class methods (#4318)

### LINKED ISSUE #4318: Class - vif reference throws CPP redeclaration error
Thanks for taking the time to report this.

```verilog
interface if_1;
  bit clk;
endinterface : if_1

class drv_c;
  virtual if_1 vif;

  virtual task run();
    @(posedge vif.clk);
   // Below line causes Verilator CPP error
  //  Commenting out below line works 
    @(posedge vif.clk);
  endtask : run
endclass : drv_c

module m;
  drv_c d_0;

  if_1 u_if_1 ();

  initial begin
    d_0 = new();
    d_0.vif = u_if_1;
    //d_0.run();
    $finish(2);
  end
endmodule : m


```

Log:
```log
Vclk_blk___024unit__03a__03adrv_c__Vclpkg__DepSet_h69446cda__0.cpp: In member function ‘virtual VlCoroutine Vclk_blk___024unit__03a__03adrv_c::__VnoInFunc_run(Vclk_blk__Syms*)’:
Vclk_blk___024unit__03a__03adrv_c__Vclpkg__DepSet_h69446cda__0.cpp:42:18: error: redeclaration of ‘CData __Vtrigprevexpr_he98b049f__0’
   42 |     CData/*0:0*/ __Vtrigprevexpr_he98b049f__0;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vclk_blk___024unit__03a__03adrv_c__Vclpkg__DepSet_h69446cda__0.cpp:19:18: note: ‘CData __Vtrigprevexpr_he98b049f__0’ previously declared here
   19 |     CData/*0:0*/ __Vtrigprevexpr_he98b049f__0;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/home/srini/tools/vlator/git_vlator/verilator//include/verilated.mk:245: Vclk_blk__ALL.o] Error 1
make: Leaving directory '/home/srini/proj/CVC_Labs/vsv_labs_2014/lab5/run_dir/obj_dir'
%Error: make -C obj_dir -f Vclk_blk.mk -j 1 exited with 2
```

What I noticed is the first reference to "posedge vif.clk" works, the second one throws this error.

What 'verilator --version' are you using?  Did you try it with the git master version?

> Verilator 5.013 devel rev v5.008-304-gdfbd711e1 (mod)

What OS and distribution are you using?

> Windows, WSL
May we assist you in trying to fix this in Verilator yourself?

> Yes, but my exposure to Verilator source code is minimal, will attempt.

### PR DESCRIPTION
**Pull request by kbieganski**
Multiple edge timing controls in class methods would cause compilation errors on the generated C++ code. This is because the `SenExprBuilder` used for these would get recreated per timing control, resulting in duplicate variable names. The fix is to have a single `SenExprBuilder` per scope.

Fixes #4318.

### CODE REVIEW

File: src/V3SenExprBuilder.h [hunk 1]
```diff
@@ -29,7 +29,7 @@
 
 class SenExprBuilder final {
     // STATE
-    AstScope* const m_scopep;  // The scope
+    AstScope* m_scopep;  // The scope
```
Comment (wsnyder) [inline src/V3SenExprBuilder.h:32]: I don't think this change is needed, you never write it outside the constructor.

File: src/V3Timing.cpp [hunk 2]
```diff
@@ -571,6 +572,7 @@ class TimingControlVisitor final : public VNVisitor {
     void visit(AstScope* nodep) override {
         VL_RESTORER(m_scopep);
         m_scopep = nodep;
+        senExprBuilder = SenExprBuilder{m_scopep};
```
Comment (wsnyder) [inline src/V3Timing.cpp:575]: I think we want a VL_RESTORER(m_senBuilderr)

File: src/V3Timing.cpp [hunk 3]
```diff
@@ -299,6 +299,7 @@ class TimingControlVisitor final : public VNVisitor {
 
     // Other
     SenTreeFinder m_finder{m_netlistp};  // Sentree finder and uniquifier
+    SenExprBuilder senExprBuilder{nullptr};
```
Comment (wsnyder) [inline src/V3Timing.cpp:302]:
```suggestion
    SenExprBuilder m_senExprBuilder{nullptr};
```

File: src/V3SenExprBuilder.h (hunk 1 above)
Comment (kbieganski) [reply src/V3SenExprBuilder.h:32]: Because C++ is the way it is, keeping `const` there deletes `SenExprBuilder`'s copy constructor (and move constructor). Other solutions include:
- Manually writing a custom copy constructor/move constructor/reinit function that copies/clears all `SenExprBuilder` fields (of which there's quite a few),
- Keeping the `SenExprBuilder` on the heap and reallocating it for each scope,
- Calling the destructor and placement `new` on it for each scope, e.g.
  ```cpp
  senExprBuilder.~SenExprBuilder();
  new (&senExprBuilder) SenExprBuilder{m_scopep}; 
  ```
  That may not be a terrible solution if we wrap it in some sort of `reconstruct(...)` utility function, I guess. Though that doesn't work with your suggestion that we need a restorer here.

File: src/V3Timing.cpp (hunk 2 above)
Comment (kbieganski) [reply src/V3Timing.cpp:575]: Can there be scopes in scopes? Then we need the copy constructor.

Comment (wsnyder) [reply src/V3Timing.cpp:575]: I think they do not next, but assert here if not accepted.

**Review by wsnyder — COMMENTED** [review]
Thanks. Feel free to squash merge when tests pass.

**Comment by kbieganski** [comment]
There were some non-deterministic failure with the previous approach, so I propose a different solution.

**Review by wsnyder — COMMENTED** [review]
Feel free to squash merge after below minor fix and tests pass.
