### PR TITLE
Fix parameter default comparison when value contains type cast (#6281)

### LINKED ISSUE #6281: Mailbox Type Mismatch Error with Parameterized Classes
**Bug Description**
Verilator reports a mailbox type mismatch error when passing a parameterized mailbox to a constructor, even when the parameter types are identical. The error suggests that mailbox__TzX and mailbox__TzY are different types, but they should be the same type.

**Error Message**
```
%Error: tb.sv:45:15: Function Argument expects a CLASSREFDTYPE 'mailbox__Tz2', got CLASSREFDTYPE 'mailbox__Tz1'
                   : ... note: In instance 'tb_top'
   45 |         drv = new(mbx);   
      |               ^~~
        ... See the manual at https://verilator.org/verilator_doc.html?v=5.039 for more assistance.
%Error: Exiting due to 1 error(s)
```

Verilator Version: latest main
Platform: Linux

Minimal Reproducible Example
```
// Base transaction class
class BaseTransaction;
    function new();
    endfunction
endclass

// Parameterized transaction class
class MyTransaction #(parameter int WIDTH = 32) extends BaseTransaction;
    bit [WIDTH-1:0] payload;
    function new(bit [WIDTH-1:0] payload = 0);
        super.new();
        this.payload = payload;
    endfunction
endclass

// Driver class expecting specific mailbox type
class MyDriver #(parameter int WIDTH = 32);
    mailbox #(MyTransaction#(WIDTH)) mbx;  // Expects specific parameterized type
    
    function new(mailbox#(MyTransaction#(WIDTH)) mbx);
        this.mbx = mbx;
    endfunction
    
    task run();
        MyTransaction#(WIDTH) tx;
        forever begin
            mbx.get(tx);
            $display("Driver got transaction with payload: %h", tx.payload);
        end
    endtask
endclass

// Environment class - this is where the error occurs
class Environment;
    MyDriver#(32) drv;
    mailbox #(MyTransaction#(32)) mbx;  // This creates one mailbox type
    
    function new();
    endfunction
    
    function void build();
        mbx = new();
        // ERROR: The mailbox type from the declaration doesn't match 
        // what the driver constructor expects due to parameter resolution
        drv = new(mbx);  // This line will cause the mailbox type mismatch error
    endfunction
    
    task run();
        fork
            drv.run();
        join_none
    endtask
endclass

// Top-level testbench module
module tb_top;
    Environment env;
    
    initial begin
        MyTransaction#(32) tx;

        env = new();
        env.build();
        env.run();
        
        // Send a transaction
        tx = new(32'hDEADBEEF);
        env.mbx.put(tx);
        
        #100;
        $finish;
    end
endmodule
```
**Steps to Reproduce**

Save the code above to a file called tb.sv
Run: `verilator --binary --timing tb.sv`
Observe the mailbox type mismatch error

**Expected Behavior**
The code should compile successfully since both mailbox declarations use MyTransaction#(32) and should resolve to the same type.

**Actual Behavior**
Verilator reports a type mismatch error suggesting that mailbox #(MyTransaction#(32)) declared in the Environment class is a different type than mailbox#(MyTransaction#(WIDTH)) where WIDTH=32 in the Driver constructor.

### PR DESCRIPTION
**Pull request by YilouWang**
## Summary

Continues the work from #6777 to fully close #6281.

The original issue — `Class_A#(32)` and `Class_A#(WIDTH_A)` (where
`WIDTH_A = 32`) being treated as different specializations — was already
resolved by the `ParameterizedHierBlocks::areSame` fallback added
separately.  A sub-case identified during that investigation remained
open: when the parameter default itself contains a type-cast literal
(e.g. `parameter byte P = byte'(8)`), passing the same numeric value
explicitly (`#(8)`) still creates a spurious second specialization,
causing type-mismatch errors on assignment between instances.

This PR fixes that remaining case with a different strategy than #6777:
instead of re-typing the pin expression to the parameter's declared type
(which requires V3Width information not yet available at this pass), we
constify only the default value and widen both constants to max(width)
for comparison.

## Changes

- In `cellPinCleanup()`, constify `modvarp->valuep()` when it is a
  `Cast` or `CastSize` node, so the default value becomes a `Const`
  available for comparison.  Restricted to `Cast`/`CastSize` to avoid
  disturbing `Pattern`/`InitArray` defaults handled in earlier branches.
- Added `paramConstsEqualAtMaxWidth()`: sign-extends both constants to
  `max(width)` before comparing, handling the width mismatch between a
  typed default and a 32-bit pin expression.
- Extended the comparison in `cellPinCleanup()` to fall back to
  `paramConstsEqualAtMaxWidth()` when `sameTree()` and `areSame()` both
  fail.

## Test

Added `test_regress/t/t_param_cast_default.{v,py}`:
- Includes the original #6281 reproducer: `Class_A#(32)` vs
  `Class_A#(WIDTH_A)` (localparam), confirming the earlier fix holds.
- New coverage for the remaining case: `byte`/`int`/signed cast defaults
  with default (`#()`) and explicit instances assigned to each other.
- Multiple instances of the same template (template mutation safety),
  module sub-instantiation.

---
Developed by PlanV GmbH, assisted with Claude Code.

Reviewed by YilouWang.

### CODE REVIEW

File: src/V3Param.cpp [hunk 1]
```diff
@@ -1235,30 +1235,29 @@ class ParamProcessor final {
...
-                                << " exprClassp=" << cvtToHex(exprClassRefp->classp())
-                                << " result=" << result);
-        return result;
+    static bool paramConstsEqualAtMaxWidth(AstConst* exprp, AstConst* origp) {
+        // Return true if two integer constants are equal after sign-extending
+        // both to max(width).  A typed parameter default (e.g. byte) is
+        // narrower than a 32-bit pin expression, so sameTree/areSame fail.
+        if (exprp->num().width() == origp->num().width()) return false;
+        if (exprp->num().isDouble() || exprp->num().isString()) return false;
+        if (origp->num().isDouble() || origp->num().isString()) return false;
```
Comment (wsnyder) [inline src/V3Param.cpp]:
```suggestion
        if (exprp->num().isOpaque() || exprp->num().isOpaque()) return false;
```

**Review by wsnyder — COMMENTED** [review]
Thanks, can you please merge master and resolve the conflicts?
