### PR TITLE
Fix duplicate static names in blocks in functions (#4144)

### LINKED ISSUE #4144: Cannot declare static variable with same name in different blocks of method
I have the following code:

```
// file: test.sv

module test;

  function do_stuff();
    begin: block0
      static int some_int;
    end
    begin: block1
      static int some_int;
    end
  endfunction 

endmodule
```

When I compile with `verilator --binary test.sv` I get:

```
%Error: test.sv:8:18: Duplicate declaration of signal: 'test.do_stuff__Vstatic__some_int'
    8 |       static int some_int;
      |                  ^~~~~~~~
        test.sv:5:18: ... Location of original declaration
    5 |       static int some_int;
      |                  ^~~~~~~~
%Error: Exiting due to 1 error(s)
```

It seems that `some_int` is put under `do_stuff` directly, not under `do_stuff.block0` and `do_stuff.block`.

### PR DESCRIPTION
**Pull request by wallento**
Static variables of functions are created in the function. When blocks in a function use identical names for static variables, we need to name those variables properly.

Fixes #4144

### CODE REVIEW

File: src/V3Begin.cpp [hunk 1]
```diff
@@ -246,7 +247,8 @@ class BeginVisitor final : public VNVisitor {
     void visit(AstVar* nodep) override {
         // If static variable, move it outside a function.
         if (nodep->lifetime().isStatic() && m_ftaskp) {
-            const std::string newName = m_ftaskp->name() + "__Vstatic__" + nodep->name();
+            const std::string newName
+                = dot(m_ftaskp->name(), m_unnamedScope) + "__Vstatic__" + nodep->name();
```
Comment (wsnyder) [inline src/V3Begin.cpp:251]:
```suggestion
                = dot(m_unnamedScope, m_ftaskp->name()) + "__Vstatic__" + nodep->name();
```

**Review by wsnyder — COMMENTED** [review]
Seems reasonable, one suggested change.  Please make a non-draft if you think is ready.

**Comment by wallento** [comment]
Are you sure? It feels a bit weird in terms of the hierarchy, or are blocks not nested inside functions?

This is the current naming of the various blocks inside the `do_stuff` function:
```
do_stuff__Vstatic__some_int
do_stuff__DOT__block0__Vstatic__some_int
do_stuff__DOT__block1__Vstatic__some_int
do_stuff__DOT__unnamedblk1__Vstatic__some_int
do_stuff__DOT__block2__DOT__block3__Vstatic__some_int
do_stuff__DOT__block2__DOT__unnamedblk2__Vstatic__some_int
```

and with your proposed change:
```
do_stuff__Vstatic__some_int
block0__DOT__do_stuff__Vstatic__some_int
block1__DOT__do_stuff__Vstatic__some_int
unnamedblk1__DOT__do_stuff__Vstatic__some_int
block2__DOT__block3__DOT__do_stuff__Vstatic__some_int
block2__DOT__unnamedblk2__DOT__do_stuff__Vstatic__some_int
```

**Comment by wallento** [comment]
Ah, or do you mean:
```
            const std::string newName
                = m_ftaskp->name() + "__Vstatic__" + dot(m_unnamedScope, nodep->name());
```

which produces:
```
do_stuff__Vstatic__some_int
do_stuff__Vstatic__block0__DOT__some_int
do_stuff__Vstatic__block1__DOT__some_int
do_stuff__Vstatic__unnamedblk1__DOT__some_int
do_stuff__Vstatic__block2__DOT__block3__DOT__some_int
do_stuff__Vstatic__block2__DOT__unnamedblk2__DOT__some_int
```

**Comment by wallento** [comment]
The last looks most sensible to me (static variables in a function named by their hierarchical name)

**Comment by wsnyder** [comment]
Last one looks best.
