### PR TITLE
Fix VPI force of bit-selected signals (#7211)

### LINKED ISSUE #7211: Fix VPI force of bit-selected signals
SV tests/70regs/30bkdr/01hdl fails due to a VPI error trying to read forcecable bit-selected signal `dut.q[1]` giving the error 

```
%Error: /svaha/wsnyder/SandBox/homecvs/v4/verilator/include/verilated_vpi.cpp:1356: getForceControlSignals: VPI force or release requested for 'dut.q[1]', but\
 vpiHandle '(nil)' of enable signal 'dut.q[1]__VforceEn' could not be cast to VerilatedVpioVar*. Ensure signal is marked as forceable
```

I improved the t_uvm_dpi test to show this (unchecked on other sims, so might not be perfect), and also added a new test based on the UVM test.

@Christian-Hecken mind taking a look when get a chance?  I think half of this overlaps what you were looking at to fix #7092.

[t_uvm_dpi.v.txt](https://github.com/user-attachments/files/25815978/t_uvm_dpi.v.txt)
[t_uvm_dpi_bkdr.v.txt](https://github.com/user-attachments/files/25815979/t_uvm_dpi_bkdr.v.txt)
[t_uvm_dpi_bkdr.py.txt](https://github.com/user-attachments/files/25815980/t_uvm_dpi_bkdr.py.txt)

### PR DESCRIPTION
**Pull request by Christian-Hecken**
Fixes #7211. I was unable to cross-check all functionality with Icarus and Xcelium due to limited feature support. Hence, I could only test single-bit forcing on Verilator, and could only check partial forcing using Xcelium for signals that are not multidimensional packed arrays, and only with descending bit ranges.
I've left out the provided `t_uvm_dpi_bkdr` from #7211 because I'm assuming these were demonstrators and you'll add the full versions when ready.

### CODE REVIEW

File: include/verilated_vpi.cpp [hunk 1]
```diff
@@ -1331,26 +1333,139 @@ auto VerilatedVpiImp::getForceControlSignals(const VerilatedVpioVarBase* const b
...
+    assert(forceEnableSignalVop->partselBits() == baseSignalVop->partselBits());
+    assert(forceValueSignalVop->partselBits() == baseSignalVop->partselBits());
+    // entSize can differ because the force enable signal can have a different vltyp than the base
+    // signal (e.g. the base signal can be of type VLVT_REAL, while the force enable signal is
+    // still of type VLVT_UINT8), but for now entSize is only used for unpacked arrays, which
+    // cannot be forced through VPI yet
+    // assert(forceEnableSignalVop->entSize() == baseSignalVop->entSize());
+    assert(forceValueSignalVop->entSize() == baseSignalVop->entSize());
+    assert(forceEnableSignalVop->varDatap() == forceEnableSignalVarp->datap());
+    assert(forceValueSignalVop->varDatap() == forceValueSignalVarp->datap());
```
Comment (wsnyder) [inline include/verilated_vpi.cpp:1466]:
```suggestion
#ifdef VL_DEBUG
    // Sanity checks: Offsets, widths, and dimensions should all match between the base signal and
    // the force control signals, so that they always refer to the same bits
    assert(forceEnableSignalVop->bitSize() == baseSignalVop->bitSize());
    assert(forceValueSignalVop->bitSize() == baseSignalVop->bitSize());
    assert(forceEnableSignalVop->indexedDim() == baseSignalVop->indexedDim());
    assert(forceValueSignalVop->indexedDim() == baseSignalVop->indexedDim());
    assert(forceEnableSignalVop->index() == baseSignalVop->index());
    assert(forceValueSignalVop->index() == baseSignalVop->index());
    assert(forceEnableSignalVop->bitOffset() == baseSignalVop->bitOffset());
    assert(forceValueSignalVop->bitOffset() == baseSignalVop->bitOffset());
    assert(forceEnableSignalVop->partselBits() == baseSignalVop->partselBits());
    assert(forceValueSignalVop->partselBits() == baseSignalVop->partselBits());
    // entSize can differ because the force enable signal can have a different vltyp than the base
    // signal (e.g. the base signal can be of type VLVT_REAL, while the force enable signal is
    // still of type VLVT_UINT8), but for now entSize is only used for unpacked arrays, which
    // cannot be forced through VPI yet
    // assert(forceEnableSignalVop->entSize() == baseSignalVop->entSize());
    assert(forceValueSignalVop->entSize() == baseSignalVop->entSize());
    assert(forceEnableSignalVop->varDatap() == forceEnableSignalVarp->datap());
    assert(forceValueSignalVop->varDatap() == forceValueSignalVarp->datap());
 #endif  // VL_DEBUG
```
