### PR TITLE
Fix virtual interface member trigger convergence (#5116)

### LINKED ISSUE #5116: Fix virtual interface "combinational region did not converge" error
Under some conditions I'm not quite sure about (but most likely involving interfaces and a class that drives the interface), a runtime error is erroneously triggered.

To reproduce, compile the following code with ``verilator --exe --build -j `nproc` --binary bug_ico.sv -o bug_ico`` (using the git master version):

```systemverilog
interface INTF ();
    logic field1;
    logic field2;
endinterface

class intf_driver_class_unused;
    virtual INTF intf;

    function new(virtual INTF intf);
        this.intf = intf;
    endfunction

    function void unused_func1();
        intf.field1 = '0;
    endfunction

    function void unused_func2();
        intf.field2 = '0;
    endfunction
endclass

module idma_backend_top ();
    typedef struct packed {     
        logic field1;
        logic x;                                            
    } s1;

    typedef struct packed {                               
        logic field2;
        logic y;
    } s2;

    // Bug happens with and without initializations
    s1 struct1 = '{1'b0, 1'b0};
    s2 struct2 = '{1'b0, 1'b0};

    assign intf.field1    = struct1.field1;
    assign struct2.field2 = intf.field2;
    assign struct1.x      = struct2.y;

    INTF intf ();

    // Doesn't change the outcome
    // initial begin
    //     intf.field1 = '0;
    //     intf.field2 = '0;
    // end
endmodule
```

(Note that the class is not even used - in the original project where this occurred it did, but while compressing it (~5k lines post-preprocessing :-( ) down to this reproducible example I found out that the class didn't even need instantiating)

The following error will show:
`%Error: bug_ico.sv:22: Input combinational region did not converge.`

Adding `-CFLAGS -DVL_DEBUG=1` additionally prints out this line before the error message:
`-V{t1,1}         'ico' region trigger index 1 is active: Internal 'ico' trigger - virtual interface: INTF`

I would appreciate any insight into what exactly is going wrong here, happy to look into it as well at some point too though. I have a feeling it has something to do with some update trigger maybe being globally on the interface rather than the individual wires of the interface, or something like that. Though I have no idea why it needs that extra driver class.

### PR DESCRIPTION
**Pull request by YilouWang**
## Summary

Fixes #5116.

Virtual interface member triggers unconditionally set a flag on every write
to a VIF-accessible interface member, regardless of whether the value actually
changed. This causes combinational convergence loops to run indefinitely,
producing a `DIDNOTCONVERGE` error. The issue was re-exposed by #6613, which
correctly connected member triggers to the trigger vector but retained the
unconditional write-flag mechanism.

This patch replaces the write-site flag mechanism with value-change comparison
at trigger evaluation time: `trigger = (current != prev); prev = current`.
Triggers now only fire when a member value actually changes, matching the
semantics of the existing `SenExprBuilder` infrastructure for regular triggers.

Also addresses the scenario reported in #6175. The gap was also encountered
while running CVV on Verilator (openhwgroup/core-v-verif#2724).

## Reproducer

```systemverilog
interface INTF();
    logic [7:0] data;
endinterface

class Writer;
    virtual INTF vif;
    function new(virtual INTF vif);
        this.vif = vif;
    endfunction
    task write_data(logic [7:0] d);
        vif.data = d;
    endtask
endclass

module t();
    logic [7:0] data;
    INTF intf_read();
    INTF intf_write();
    assign intf_read.data = data;
    assign data = intf_write.data;
    virtual INTF vif_read, vif_write;
    Writer writer;

    initial begin
        vif_write = intf_write;
        vif_read  = intf_read;
        vif_write.data = 8'hA5;
        #1ns;
        writer = new(vif_write);
        #1ns;
        writer.write_data(8'hB7);
        #1ns;
        if (vif_read.data !== 8'hB7) $stop;
        $write("*-* All Finished *-*\n");
        $finish;
    end
endmodule
```

On master (test is skipped by #6613; un-skipping and running produces):
```
%Error-DIDNOTCONVERGE: t.sv:19: NBA region did not converge after '--converge-limit' of 10000 tries
```

## Changes

- `V3SchedVirtIface.cpp`: Removed write-site `AstExprStmt` flag wrapping. Now
  collects all interface instance `AstVarScope` nodes with `sensIfacep()` set,
  grouped by `(AstIface*, AstVar*)`. Also extended `writesToVirtIface()` to
  cover `sensIfacep()` variables for `AlwaysPost` lifetime optimization.
- `V3SchedTrigger.cpp`: Added `TriggerKit::addValueChangeTriggerAssignment()`
  which creates per-instance prev variables, compares `inst != prev` (with
  `UNPACKED_NEQ` for unpacked arrays), ORs results into a single extra trigger
  bit, and updates prev after comparison. Skips non-comparable types (event,
  string, chandle) to avoid C++ compile errors on e.g. `VlEvent != VlEvent`.
- `V3Sched.h`: Changed `VirtIfaceTriggers` to store `MemberTriggerInfo`
  (vector of instance `AstVarScope*`) instead of flag `AstVarScope*`. Made
  `IfaceMember::operator<` deterministic (compare by name, not pointer).
- `V3Sched.cpp`: Updated `addVirtIfaceTriggerAssignments()` signature and
  both call sites (ICO and ACT) to pass `netlistp` and `initFuncp`.

## Test

- Unskipped `test_regress/t/t_virtual_interface_member_trigger.{v,py}` -- was
  marked broken by #6613. Added `--timing` flag to driver.
- Unskipped `test_regress/t/t_virtual_interface_member_trigger_real.{v,py}` --
  was marked broken by #6613. Added `--timing` flag to driver.

---
Developed by PlanV GmbH, assisted with Claude Code.

Reviewed by YilouWang.

### CODE REVIEW

**Comment by wsnyder** [comment]
Intersects with #7130?

**Comment by YilouWang** [comment]
Ah, Yes, didn't notice #7130 was open — sorry about the overlap.

Both fix #5116 but differently: #7130 keeps the write-site ExprStmt and makes it conditional (`trigger = old != new`) for AssignW, with an OrderGraphBuilder change to avoid cycles. This PR removes the ExprStmt entirely and does prev/curr comparison in the trigger eval function, covering all write paths uniformly.

Personally, I think this PR is cleaner but I'm fine with either approach. Let me know how you'd like to proceed @wsnyder @gezalore — happy to close this if #7130 is preferred, or we can cherry-pick ideas from both.

**Comment by YilouWang** [comment]
One update: Added sensIfacep() to ICO and ACT ordering lambdas, matching the existing NBA lambda. Needed because value-change detection relies on the ordering lambda to associate interface member variables with VIF triggers (the old ExprStmt mechanism covered this implicitly).

**Comment by wsnyder** [comment]
@gezalore to comment; this passes UVM tests so I'm good if @gezalore wants to merge it. If there are later material changes I'll want to retest.

File: src/V3SchedVirtIface.cpp [hunk 1]
```diff
@@ -16,21 +16,19 @@
...
 // V3SchedVirtIface's Transformations:
 //
-// Each interface type written to via virtual interface, or written to normally but read via
-// virtual interface:
-//     Create a trigger var for it
-// Each statement:
-//     If it writes to a virtual interface, or to a variable read via virtual interface:
-//         Set the corresponding trigger to 1
-//         If the write is done by an AssignDly, the trigger is also set by AssignDly
+// Collect all interface instance VarScopes that are read via virtual interfaces
```
Comment (gezalore) [inline src/V3SchedVirtIface.cpp]: What is a 'interface instance VarScopes'? If this means something to you please define it very clearly and avoid overloading terms. Generally 'instance' means an `AstCell` of similar, or a class instance, neither of which is a 'VarScope'.

File: src/V3SchedVirtIface.cpp [hunk 2]
```diff
@@ -40,102 +38,50 @@ namespace {
...
-        if (nodep->user1SetOnce()) return;
-        AstIface* ifacep = nullptr;
-        AstVar* memberVarp = nullptr;
-        if (nodep->varp()->isVirtIface()) {
-            if (AstMemberSel* const memberSelp = VN_CAST(nodep->firstAbovep(), MemberSel)) {
-                ifacep = VN_AS(nodep->varp()->dtypep(), IfaceRefDType)->ifacep();
-                memberVarp = memberSelp->varp();
+    // Collect all VarScopes whose varp has sensIfacep set -- these are interface
+    // member instances that are read through virtual interfaces and need monitoring.
+    void collectInstanceVarScopes() {
```
Comment (gezalore) [inline src/V3SchedVirtIface.cpp]: Can we make this a visit(AstVarScope*) instead? I don't see a reason why we need to traverse the whole netlist twice.

Also, I think `sensIfacep()` is set for all AstVar defined in an interface that is accessed via a MemberSel (e.g. via simple interface port), so this would create triggers for far more things than is needed.

File: test_regress/t/t_virtual_interface_member_trigger.py [hunk 3]
```diff
@@ -9,11 +9,9 @@
 
 import vltest_bootstrap
 
-test.skip("Test is broken, see #6613")
-
 test.scenarios('simulator')
 
-test.compile(verilator_flags2=['--binary'])
+test.compile(verilator_flags2=['--binary', '--timing'])
```
Comment (gezalore) [inline test_regress/t/t_virtual_interface_member_trigger.py]: `--binary` implies `--timing`, ditto other test.

File: src/V3Sched.cpp [hunk 4]
```diff
@@ -547,7 +549,9 @@ AstNode* createInputCombLoop(AstNetlist* netlistp, AstCFunc* const initFuncp,
                 out.push_back(inputChanged);
             }
             if (varp->isWrittenByDpi()) out.push_back(dpiExportTriggered);
-            if (vscp->varp()->isVirtIface()) {
+            // Check both sensIfacep() (interface members read via VIF) and
```
Comment (gezalore) [inline src/V3Sched.cpp]: > sensIfacep() (interface members read via VIF) 

I don't think that's what `sensIfacep()` means (It's also set for those referenced through non-virtual ones)

File: src/V3SchedTrigger.cpp [hunk 5]
```diff
@@ -426,6 +426,101 @@ void TriggerKit::addExtraTriggerAssignment(AstVarScope* vscp, uint32_t index, bo
     m_compVecp->addStmtsp(setp);
 }
 
+// Value-change detection for virtual interface member triggers.
+// Parallel to SenExprBuilder::createTerm(ET_CHANGED) / getPrev(), but operates on
+// multiple interface instance VarScopes OR'd into a single extra trigger bit.
```
Comment (gezalore) [inline src/V3SchedTrigger.cpp]: What's the point of doing the OR reduction here? I don't see any benefit, only complication. There should be a single trigger per interface member that might be written through a virtual inteface.

File: src/V3SchedTrigger.cpp [hunk 6]
```diff
@@ -426,6 +426,101 @@ void TriggerKit::addExtraTriggerAssignment(AstVarScope* vscp, uint32_t index, bo
...
+    AstNodeExpr* changedp = nullptr;
+    AstNode* updatesp = nullptr;
+    for (AstVarScope* const instVscp : instanceVscps) {
+        AstNodeDType* const dtypep = instVscp->dtypep()->skipRefp();
+
+        // Skip types that do not support value-change comparison (events, chandles, strings)
+        if (const AstBasicDType* const bdtypep = VN_CAST(dtypep, BasicDType)) {
+            if (bdtypep->isEvent() || bdtypep->isString()
+                || bdtypep->keyword() == VBasicDTypeKwd::CHANDLE) {
+                continue;
```
Comment (gezalore) [inline src/V3SchedTrigger.cpp]: E_UNSUPPORTED would probably be better than silently ignore and to the wrong thing.

**Comment by gezalore** [comment]
Marking draft until ready.

**Comment by YilouWang** [comment]
@gezalore  Thanks for the guidance of the three-case design. Totally agree that we should adopt a fine granularity strategy.

I have restructured the logic and when merged with latest master, I noticed that this also subsumes #7323  (the member-level filtering fix) since the VscpSensMap lookup provides both member-level and instance-level precision.

File: src/V3SchedVirtIface.cpp [hunk 7]
```diff
@@ -40,103 +38,71 @@ namespace {
...
-        AstIface* ifacep = nullptr;
-        AstVar* memberVarp = nullptr;
-        if (nodep->varp()->isVirtIface()) {
-            if (AstMemberSel* const memberSelp = VN_CAST(nodep->firstAbovep(), MemberSel)) {
-                ifacep = VN_AS(nodep->varp()->dtypep(), IfaceRefDType)->ifacep();
-                memberVarp = memberSelp->varp();
+    // VISITORS
+    void visit(AstMemberSel* nodep) override {
+        // Detect writes through VIF: the MemberSel's fromp resolves to a virtual interface type.
+        // Handles both direct VIF access (vif.member) and class chain (obj.vif.member).
```
Comment (gezalore) [inline src/V3SchedVirtIface.cpp:63]: Do the same in `writesToVirtIface` while you are at it.

File: test_regress/t/t_virtual_interface_trigger_unsup.v [hunk 8]
```diff
@@ -0,0 +1,19 @@
+// DESCRIPTION: Verilator: Verilog Test module
+//
+// This file ONLY is placed under the Creative Commons Public Domain.
+// SPDX-FileCopyrightText: 2025 PlanV GmbH
```
Comment (gezalore) [inline test_regress/t/t_virtual_interface_trigger_unsup.v]: Year update

**Comment by wsnyder** [comment]
Passes UVM, feel free to merge once get last round of fixes.
