### PR TITLE
Fix VPI callback list iteration

### LINKED ISSUE #2536: Dual clock, dual run testbench freezes
Hi,

I'm using Verilator 4.100 with cocotb 1.4.0.
The cocotb bug is https://github.com/cocotb/cocotb/issues/2051 and has some debugging by the maintainers but no workaround. It was suggested this is likely a Verilator issue, so I'm filling this bug report.

I have made this minimal repro: https://gist.github.com/bluecmd/fe70d5279bfcaca470c6556ccd502933.

- I set up two identical tests creating two clocks and one AvalonSTMonitor
- If I run a single test using `make TESTCASE=test_a` either test works.
- If I make the test only use a single clock, running both tests works.
- If I initialize the AvalonSTMonitor before calling await on anything both tests work.
- Using `make SIM=icarus` works fine.

As can be seen in the debug log in the other bug cocotb claims to return the control to Verilator and then nothing happens.

@ktbarrett for visibility.

### PR DESCRIPTION
**Pull request by garmin-mjames**
Actually fix #2536. This is a follow-on to #2588 with a test.

Saving the **end()** iterator isn't enough, as it points to a non-existent element after the last element in the list.
Callbacks added with **push_back()** are inserted before it, so the same problem still exists.

We need to get the last element in the list when the loop starts, and exit once it's been processed.
I played with keeping an exit condition in the for loop, but I couldn't solve a segfault I was getting when dealing with the last element being erased.

If you have suggestions on a different approach, they are welcome.

In the test, I needed the list to have at least 2 callbacks at the start of the loop to get the error condition on master (thus the filler callback). With only 1 callback, the `it++` set it to the end iterator before a new callback was added and the loop was exited.

### CODE REVIEW

File: include/verilated_vpi.cpp [hunk 1]
```diff
@@ -494,10 +499,14 @@ class VerilatedVpiImp {
         bool called = false;
         typedef std::set<VerilatedVpioVar*> VpioVarSet;
         VpioVarSet update;  // set of objects to update after callbacks
-        const auto end = cbObjList.end();  // prevent looping over newly added elements
-        for (auto it = cbObjList.begin(); it != end;) {
+        if (cbObjList.empty()) { return called; }
```
Comment (wsnyder) [inline include/verilated_vpi.cpp:502]:
```suggestion
        if (cbObjList.empty()) return called;
```

Style nit - similar elsewhere.

File: include/verilated_vpi.cpp [hunk 2]
```diff
@@ -494,10 +499,14 @@ class VerilatedVpiImp {
...
+        const auto last = std::prev(cbObjList.end());  // prevent looping over newly added elements
+        bool is_last;
+        for (auto it = cbObjList.begin();;) {
+            is_last = it == last;
```
Comment (wsnyder) [inline include/verilated_vpi.cpp:506]:
```suggestion
        for (auto it = cbObjList.begin(); true;) {
            // cbReasonRemove sets to nullptr, so we know on removal the old end() will still exist
            bool was_last = it == last;
```

Think "was_last" better indicates intent. Similar above as per codacy.

**Review by wsnyder — COMMENTED** [review]
Logically makes sense - of course I thought the old version did too ;)
