### PR TITLE
Fix V3SplitVar test stability

### LINKED ISSUE #2407: Error instability in V3SplitVar
@yTakatsukasa

1. We noticed that the t_split_var_1_bad test was occasionally failing e.g.

https://travis-ci.com/github/verilator/verilator/jobs/343524573

The test fails because the error output changes.  I believe this is because in V3SplitVar.cpp's split() there is an unordered_map which can report errors.  

Would you be willing to take a look?   Note we wouldn't want to just make it a std::map as a key of pointers still would not be stable - it needs some stable sort.

2.  I've been trying to look at code coverage, if you look at the coverage report here: https://codecov.io/gh/verilator/verilator/src/master/src/V3SplitVar.cpp

you'll see a bunch of lines that the tests aren't covering. My primary concern would be lines unrelated to errors, but ideally we'd cover the user errors too.  No need to cover internal errors - I tried to turn off coverage on all internal-only errors but might have missed some.

Thanks!

### PR DESCRIPTION
**Pull request by yTakatsukasa**
This PR fixes #2407 .
AstNodeComparator is used in all associative container.

e48bc11 reverts changes of t_split_var_1_bad.{pl,out} in 5a622fd9db43592d996883a1051c87983e2439ee. (driver.pl and t_vlcov_merge.pl are not reverted).

### CODE REVIEW

File: src/V3SplitVar.cpp [hunk 1]
```diff
@@ -228,6 +228,25 @@ const char* const SplitVarImpl::notSplitMsg
...
+            return afp->firstLineno() < bfp->firstLineno();
+        if (afp->firstColumn() != bfp->firstColumn())
+            return afp->firstColumn() < bfp->firstColumn();
+        // Don't comapre its filename because it is expensive.
+        // Line number and column is practically enough.
+        // The comparison of raw pointer here is just in case.
+        // The comparison of this pointer may differ on different run,
+        // but this is just warning message order. (mostly for CI)
+        // Verilated result is same anyway.
+        return ap < bp;
```
Comment (wsnyder) [inline src/V3SplitVar.cpp:246]: Suggest make an operatorCompare() in V3FileLine.h near the operator== and compare that.  Note filenames are stored as numbers so you can compare filenameno (a number).  When we get to C++20 this can become the spaceship operator.

File: src/V3SplitVar.cpp [hunk 2]
```diff
@@ -336,30 +358,11 @@ class UnpackRefMap {
...
-};
-
 // Found nodes for SplitPackedVarVisitor
 struct RefsInModule {
-    std::set<AstVar*> m_vars;
-    std::set<AstVarRef*> m_refs;
-    std::set<AstSel*> m_sels;
+    std::set<AstVar*, AstNodeComparator> m_vars;
+    std::set<AstVarRef*, AstNodeComparator> m_refs;
+    std::set<AstSel*, AstNodeComparator> m_sels;
```
Comment (wsnyder) [inline src/V3SplitVar.cpp:365]: Pleas make typedefs for these three, then use them here and below so the iterators are cleaner. Thanks.

File: src/V3SplitVar.cpp (hunk 1 above)
Comment (yTakatsukasa) [reply src/V3SplitVar.cpp:246]: Thanks for the info.
Then the comparison function can check m_filenameno first so that the sorted result would be natural. (filename -> line no. -> column no)

Let me confirm the signature. Do you mean 1. below ?
1. bool FileLine::operatorCompare(const FileLine&) const;
2. bool FileLine::operator < (const FileLine&) const;

Comment (wsnyder) [reply src/V3SplitVar.cpp:246]: I think you need a operatorCompare as need -1, 0 and 1.

Comment (wsnyder) [reply src/V3SplitVar.cpp:246]: If you can stable sort with just operator< then that's better instead.

Comment (yTakatsukasa) [reply src/V3SplitVar.cpp]: You are right. If I just sort FileLine itself, `operator <` is enough.
But I'd like to also know if two FileLine are same or not.
So returning +-1, 0 is more convenient.
Added in 00ff30b5ad712aa74e6bff5a3c67154195deb820.

File: src/V3SplitVar.cpp (hunk 2 above)
Comment (yTakatsukasa) [reply src/V3SplitVar.cpp]: I added typefs in 00ff30b5ad712aa74e6bff5a3c67154195deb820.

File: src/V3FileLine.h [hunk 3]
```diff
@@ -265,6 +265,19 @@ class FileLine {
                 && m_lastLineno == rhs.m_lastLineno && m_lastColumn == rhs.m_lastColumn
                 && m_filenameno == rhs.m_filenameno && m_warnOn == rhs.m_warnOn);
     }
+    // Returns -1 if (*this) should come before rhs after sorted. 1 for the opposite case. 0 for
+    // equivalent.
+    int operatorCompare(const FileLine& rhs) const {
+        if (m_filenameno != rhs.m_filenameno) return m_filenameno < rhs.m_filenameno ? -1 : 1;
```
Comment (wsnyder) [inline src/V3FileLine.h:271]:
```suggestion
        if (m_filenameno != rhs.m_filenameno) return (m_filenameno < rhs.m_filenameno) ? -1 : 1;
```
Ditto elsewhere (style tools complain otherwise).

File: src/V3SplitVar.cpp [hunk 4]
```diff
@@ -277,6 +287,9 @@ class UnpackRef {
     }
     bool lvalue() const { return m_lvalue; }
     bool ftask() const { return m_ftask; }
+    bool operator<(const UnpackRef& other) const {
+        return AstNodeComparator()(this->m_nodep, other.m_nodep);
```
Comment (wsnyder) [inline src/V3SplitVar.cpp:291]:
```suggestion
        return AstNodeComparator()(m_nodep, other.m_nodep);
```

File: src/V3SplitVar.cpp [hunk 5]
```diff
@@ -894,15 +888,16 @@ class PackedVarRef {
     AstBasicDType* m_basicp;  // Cache the ptr since varp->dtypep()->basicp() is expensive
     bool m_dedupDone;
     static void dedupRefs(std::vector<PackedVarRefEntry>& refs) {
-        vl_unordered_map<AstNode*, size_t> nodes;
+        // Use raw pointer to dedup
+        typedef std::map<AstNode*, size_t> NodeIndices;
```
Comment (wsnyder) [inline src/V3SplitVar.cpp:892]: This I think can remain an vl_unordered_map.  Or if not (if it needs ordering), then it presumably needs your compare function.

File: src/V3FileLine.h (hunk 3 above)
Comment (yTakatsukasa) [reply src/V3FileLine.h]: Add parenthesis in cbd1823

File: src/V3SplitVar.cpp (hunk 4 above)
Comment (yTakatsukasa) [reply src/V3SplitVar.cpp]: I did so in a42bd99

File: src/V3SplitVar.cpp (hunk 5 above)
Comment (yTakatsukasa) [reply src/V3SplitVar.cpp]: Oh, thank you. I dropped the predicate by mistake in 00ff30.
Resurrected in b5ae9be861f6d528a8d2aa5f9e9ac3b1b6f2da48.
