### PR TITLE
Optimize mux with UInt To OneHot (#6760)

### LINKED ISSUE #6760: Performance regression in Chisel 7.3.0 generated code
Can you please attach an example that shows the issue or missing feature?

Please see: https://github.com/cyyself/verilator-chisel7-regression

We discovered a significant performance regression in Verilator simulation when using Chisel 7 compared to Chisel 6 for designs that utilize `Mux1H` with a large number of inputs with LLVM-19.

```scala
class Test extends RawModule {
  val width = 7 // 2**7 = 128 entries
  val io = IO(new Bundle {
    val in = Input(Vec((1 << width), UInt(32.W)))
    val sel = Input(UInt(width.W))
    val out = Output(UInt(32.W))
  })

  val sel = UIntToOH(io.sel, 1 << width)
  io.out := Mux1H(sel, io.in)
}
```

In Chisel 6.7.0, the Verilog will be like:

```systemverilog
  assign io_out =
    (io_sel == 7'h0 ? io_in_0 : 32'h0) | (io_sel == 7'h1 ? io_in_1 : 32'h0)
    | (io_sel == 7'h2 ? io_in_2 : 32'h0) | (io_sel == 7'h3 ? io_in_3 : 32'h0)
    | (io_sel == 7'h4 ? io_in_4 : 32'h0) | (io_sel == 7'h5 ? io_in_5 : 32'h0)
    | (io_sel == 7'h6 ? io_in_6 : 32'h0) | (io_sel == 7'h7 ? io_in_7 : 32'h0)
    | (io_sel == 7'h8 ? io_in_8 : 32'h0) | (io_sel == 7'h9 ? io_in_9 : 32'h0)
    // ... snip ...
```
In Chisel 7.3.0, the Verilog will be like:

```systemverilog
  wire [127:0] sel = 128'h1 << io_sel;	// src/main/scala/chisel3/util/OneHot.scala:65:12
  assign io_out =
    (sel[0] ? io_in_0 : 32'h0) | (sel[1] ? io_in_1 : 32'h0) | (sel[2] ? io_in_2 : 32'h0)
    | (sel[3] ? io_in_3 : 32'h0) | (sel[4] ? io_in_4 : 32'h0) | (sel[5] ? io_in_5 : 32'h0)
    | (sel[6] ? io_in_6 : 32'h0) | (sel[7] ? io_in_7 : 32'h0) | (sel[8] ? io_in_8 : 32'h0)
    | (sel[9] ? io_in_9 : 32'h0) | (sel[10] ? io_in_10 : 32'h0)
    // ... snip ...
```

It has no difference in functionality, but let's look at the Verilator output for both versions.

In Chisel 6.7.0, Verilator generates the following code:

```cpp
    vlSelfRef.Test__DOT____VdfgBinToOneHot_Tab_h807d22cc_0_0[vlSelfRef.Test__DOT____VdfgBinToOneHot_Pre_h807d22cc_0_0] = 0U;
    vlSelfRef.Test__DOT____VdfgBinToOneHot_Tab_h807d22cc_0_0[vlSelfRef.io_sel] = 1U;
    vlSelfRef.Test__DOT____VdfgBinToOneHot_Pre_h807d22cc_0_0 
        = vlSelfRef.io_sel;
    __Vdeeptemp_h9151389e__0 = ((vlSelfRef.Test__DOT____VdfgBinToOneHot_Tab_h807d22cc_0_0
                                 [9U] ? vlSelfRef.io_in_9
                                  : 0U) | ((vlSelfRef.Test__DOT____VdfgBinToOneHot_Tab_h807d22cc_0_0
                                            [0x0aU]
                                             ? vlSelfRef.io_in_10
                                             : 0U) 
                                           | ((vlSelfRef.Test__DOT____VdfgBinToOneHot_Tab_h807d22cc_0_0
                                               [0x0bU]
                                                ? vlSelfRef.io_in_11
                                                : 0U) 
```

In Chisel 7.3.0, Verilator generates the following code:

```cpp
    __Vtemp_1[0U] = 1U;
    __Vtemp_1[1U] = 0U;
    __Vtemp_1[2U] = 0U;
    __Vtemp_1[3U] = 0U;
    VL_SHIFTL_WWI(128,128,7, __Vtemp_2, __Vtemp_1, (IData)(vlSelfRef.io_sel));
    __Vtemp_3[0U] = 1U;
    __Vtemp_3[1U] = 0U;
    __Vtemp_3[2U] = 0U;
    __Vtemp_3[3U] = 0U;
    VL_SHIFTL_WWI(128,128,7, __Vtemp_4, __Vtemp_3, (IData)(vlSelfRef.io_sel));
    __Vtemp_5[0U] = 1U;
    __Vtemp_5[1U] = 0U;
    __Vtemp_5[2U] = 0U;
    __Vtemp_5[3U] = 0U;
    VL_SHIFTL_WWI(128,128,7, __Vtemp_6, __Vtemp_5, (IData)(vlSelfRef.io_sel));
    __Vtemp_7[0U] = 1U;
    __Vtemp_7[1U] = 0U;
    __Vtemp_7[2U] = 0U;
    __Vtemp_7[3U] = 0U;
    // ... snip ...
```

and Then:

```cpp
    __Vdeeptemp_h20de80fe__0 = (((0x00000400U & __Vtemp_20[0U])
                                  ? vlSelfRef.io_in_10
                                  : 0U) | (((0x00000800U 
                                             & __Vtemp_22[0U])
                                             ? vlSelfRef.io_in_11
                                             : 0U) 
                                           | (((0x00001000U 
                                                & __Vtemp_24[0U])
                                                ? vlSelfRef.io_in_12
                                                : 0U) 
    // ... snip ...
```

As we can see, in Chisel 6.7.0, Verilator is able to optimize the Mux1H implementation into a simple array lookup, while in Chisel 7.3.0, Verilator generates a lot of shift operations and bitwise AND operations, which significantly increases the complexity of the generated code and leads to performance degradation during simulation.

As a result, let's look at the `analyze/chisel6.s` and `analyze/chisel7.s` files:

```asm
void VTest___024root___ico_sequent__TOP__0(VTest___024root* vlSelf) {
     b40:	55                   	push   %rbp
# ... snip ...
    285c:	e9 01 ee ff ff       	jmp    1662 <_Z37VTest___024root___ico_sequent__TOP__0P15VTest___024root+0xb22>
```

The code size is only `0x1d1c` bytes for Chisel 6.7.0, while for Chisel 7.3.0:

```asm
void VTest___024root___ico_sequent__TOP__0(VTest___024root* vlSelf) {
     b10:	55                   	push   %rbp
    bbca:	eb b4                	jmp    bb80 <_Z37VTest___024root___ico_sequent__TOP__0P15VTest___024root+0xb070>
```

The code size is `0xb0ba` bytes for Chisel 7.3.0, which is more then **6x** larger than Chisel 6.7.0.

What 'verilator' command line do we use to run your example?

```bash
verilator --build -O3 --cc rtl/chisel6/Test.sv --CFLAGS "-O3 -g"
verilator --build -O3 --cc rtl/chisel7/Test.sv --CFLAGS "-O3 -g"
```

What 'verilator --version' are you using?  Did you try it with the git master version?  Did you try it with other simulators?

Self-compiled from the recent master branch 18dd44e97.

What OS and distribution are you using?

Debian sid.

May we assist you in trying to fix this in Verilator yourself?

Yes!

### PR DESCRIPTION
**Pull request by cyyself**
In Chisel 7.3, Mux1H with UIntToOH selector is not optimized to ArraySel operations. This commit adds an optimization pass to convert such patterns to ArraySel operations in the DFG.

This fixes #6760

### CODE REVIEW

**Comment by cyyself** [comment]
We can also see the differences using: https://github.com/cyyself/verilator-chisel7-regression

File: src/V3DfgPasses.cpp [hunk 1]
```diff
@@ -173,6 +173,18 @@ void V3DfgPasses::binToOneHot(DfgGraph& dfg, V3DfgBinToOneHotContext& ctx) {
             if (!widthOk(srcp) || !useOk(redOrp, true)) continue;
             val = 0;
             inv = true;
+        } else if (DfgSel* const selp = vtx.cast<DfgSel>()) {
+            // Special case: Sel(ShiftL(1, src),lsb)
+            DfgVertex* const selSrcp = selp->fromp();
+            if (!selSrcp) continue;
+            DfgShiftL* const shiftLp = selSrcp->cast<DfgShiftL>();
+            if (!shiftLp) continue;
```
Comment (gezalore) [inline src/V3DfgPasses.cpp]: `selp->fromp()` is never null here

```suggestion
            DfgShiftL* const shiftLp = selp->fromp()->cast<DfgShiftL>();
            if (!shiftLp) continue;
```

File: src/V3DfgPasses.cpp [hunk 2]
```diff
@@ -173,6 +173,18 @@ void V3DfgPasses::binToOneHot(DfgGraph& dfg, V3DfgBinToOneHotContext& ctx) {
...
+            DfgConst* const constp = shiftLp->lhsp()->cast<DfgConst>();
+            if (!constp || !useOk(selp, false)) continue;
+            if (!constp->hasValue(1)) continue;
+            srcp = shiftLp->rhsp();
```
Comment (gezalore) [inline src/V3DfgPasses.cpp:184]: Also check `widthOk(srcp)` like elsewhere to make sure we don't try to generate too big of a table.

Comment (cyyself) [reply src/V3DfgPasses.cpp:184]: It's intended since the `srcp` here can be very very huge, as it expands from the value.

**Comment by cyyself** [comment]
It fails XiangShan compilation now. I should have some time to debug.

File: src/V3DfgPasses.cpp (hunk 2 above)
Comment (cyyself) [reply src/V3DfgPasses.cpp:184]: Oh! Sorry, I misunderstood this comment. `srcp` should be checked. Previously, I think that's about `selp`.

**Comment by cyyself** [comment]
It's ready now. I forgot to check the width of `DfgSel` previously.

I also tested this with XiangShan `kunminghu-v3` branch with commit https://github.com/openxiangShan/xiangshan/commit/dfd99cfebdcabb5cfb75c77d8697d423ef09b5fe.

On Intel Core i9-13900K with LLVM-21 with:

```bash
make emu PGO_WORKLOAD=`realpath ready-to-run/coremark-2-iteration.bin` EMU_THREADS=8 LLVM_PROFDATA=llvm-profdata -j `nproc`
```

and run 

```bash
numactl --physcpubind=0-15 ./build/emu -i ready-to-run/coremark-2-iteration.bin --no-diff  2>/dev/null
```

Using verilator master commit https://github.com/verilator/verilator/commit/a1cd7d1f3a4c4d9e76c2ac1bfaf510ee20c20df6:

```console
CoreMark Iterations/Sec 843
Core 0: HIT GOOD TRAP at pc = 0x80001ca0
Core-0 instrCnt = 663,683, cycleCnt = 295,698, IPC = 2.244462
Seed=0 Guest cycle spent: 295,703 (this will be different from cycleCnt if emu loads a snapshot)
Host time spent: 56,228ms
```

After this PR commit https://github.com/verilator/verilator/commit/f85b0ec2114b1ac4bce487b9b8adf2cf60466eb1:

```console
CoreMark Iterations/Sec 843
Core 0: HIT GOOD TRAP at pc = 0x80001ca0
Core-0 instrCnt = 663,683, cycleCnt = 295,698, IPC = 2.244462
Seed=0 Guest cycle spent: 295,703 (this will be different from cycleCnt if emu loads a snapshot)
Host time spent: 35,768ms
```

**Comment by gezalore** [comment]
Please add a test for this in t_dfg_bin_to_one_hot.v then update the expected statistics in t_dfg_bin_to_one_hot.py

**Comment by cyyself** [comment]
> Please add a test for this in t_dfg_bin_to_one_hot.v then update the expected statistics in t_dfg_bin_to_one_hot.py

Done

File: src/V3DfgPasses.cpp [hunk 3]
```diff
@@ -173,6 +173,19 @@ void V3DfgPasses::binToOneHot(DfgGraph& dfg, V3DfgBinToOneHotContext& ctx) {
...
+            if (selp->width() != 1) continue;
+            DfgShiftL* const shiftLp = selp->fromp()->cast<DfgShiftL>();
+            if (!shiftLp) continue;
+            DfgConst* const constp = shiftLp->lhsp()->cast<DfgConst>();
+            if (!constp || !useOk(selp, false)) continue;
+            if (!constp->hasValue(1)) continue;
+            srcp = shiftLp->rhsp();
+            if (!widthOk(srcp)) continue;
+            val = selp->lsb();
+            if (val >= constp->width()) continue;
```
Comment (gezalore) [inline src/V3DfgPasses.cpp]: All DfgSel are within bounds in Dfg, so this branch is unnecessary. Please remove then good to merge.

Comment (cyyself) [reply src/V3DfgPasses.cpp]: I want to preserve this line for some edge cases. Look at this example:

```systemverilog
  wire [3:0] io_sel;
  wire [15:0] sel = {8'h1} << io_sel;

  assign io_out =
    (sel[0] ? io_in_0 : 32'h0) | (sel[1] ? io_in_1 : 32'h0) | (sel[2] ? io_in_2 : 32'h0)
    | (sel[3] ? io_in_3 : 32'h0) | (sel[4] ? io_in_4 : 32'h0) | (sel[5] ? io_in_5 : 32'h0)
    | (sel[6] ? io_in_6 : 32'h0) | (sel[7] ? io_in_7 : 32'h0) | (sel[8] ? io_in_8 : 32'h0)
    | (sel[9] ? io_in_9 : 32'h0) | (sel[10] ? io_in_10 : 32'h0)
    | (sel[11] ? io_in_11 : 32'h0) | (sel[12] ? io_in_12 : 32'h0)
    | (sel[13] ? io_in_13 : 32'h0) | (sel[14] ? io_in_14 : 32'h0)
    | (sel[15] ? io_in_15 : 32'h0);
```

In this case, I want to keep the width of `sel` as 8 bits shifted by `io_sel`, instead of changing it to 16 bits.

By now, Verilator will report a warning like this:

```console
%Warning-WIDTHEXPAND: rtl/chisel7/Test.sv:23:28: Operator SHIFTL expects 16 bits on the LHS, but LHS's REPLICATE generates 8 bits.
                                               : ... note: In instance 'Test'
   23 |   wire [15:0] sel = {8'h1} << io_sel;
      |                            ^~
                      ... For warning description see https://verilator.org/warn/WIDTHEXPAND?v=5.043
                      ... Use "/* verilator lint_off WIDTHEXPAND */" and lint_on around source to disable this message.
```

And the LHS of the shift operation is expanded from 8 bits to 16 bits. However, it's not aligned with Verilog's behavior, which states that the width of the result should keep the LHS's width as 8 bits. Although it's not supported by Verilator, I want to keep checking the width if Verilator can support it in the future.

Comment (gezalore) [reply src/V3DfgPasses.cpp]: > However, it's not aligned with Verilog's behavior, 

It is aligned with Verilog's definition, and all simulator will execute this by first expanding the LHS of the shift to 16 bits. This is defined behaviour in the standard (for better or worse) and Verilator follows it.

In any case, by the time the logic reaches Dfg, it will have gone through all the width fixups, and a `DfgSel` vertex where the selected bits are out of bounds for `DfgSel::fromp()` cannot exist at run-time (nor will one ever exist in the future, it's by design of the representation).

Please remove 

```
            if (val >= constp->width()) continue;
```

Comment (cyyself) [reply src/V3DfgPasses.cpp]: OK. Removed and rebased to the newest master.
