### PR TITLE
Fix recursive default assignment for subarrays (#4589)

### LINKED ISSUE #2491: Unsupported: The multidimensional array defined parameter is assigned with '{default:0}
> Verilator version:
```
Verilator 4.038 2020-07-11 rev v4.036-114-g0cd4a57ad
```
> Testcase
```systemverilog
//t_param_err.v
/* verilator lint_off DECLFILENAME */
module t;
/* verilator lint_on DECLFILENAME */
parameter p [1:0][7:0][7:0] = '{default:0};
initial begin
if (p[0][0][0] != 1'b0) $stop;
$write("*-* All Finished *-*\n");
$finish;
end
endmodule
```
> Then translated by verilator with the following  command: _**verilator -Wall --sc t_param_err.v**_ , I meet a error like this:
```
%Error: t_param_err.v:7:15: Illegal assignment of constant to unpacked array
                          : ... In instance t
    7 |       if (p[0][0][0] != 1'b0) $stop;
      |               ^
%Error: Exiting due to 1 error(s)
```
> If the following statement is modified in this way, translated successfully by verilator.
```systemverilog
parameter p [1:0][7:0][7:0] = '{default:0}; 
```
> changed to
```systemverilog
parameter p [1:0][7:0][7:0] = '{default:'{default:'{default:0}}}; 
```
> I think it might be a bug, what's your opinion?

### LINKED ISSUE #4589: default keyword does not apply recursively to subarrays in an array assignment expression
In array assignment patterns, verilator does not apply the default keyword recursively to subarrays.

For example, in this case:
```verilog
module dut;
   int a[4][4] = '{default: 0};
endmodule
```
verilating gives this error:
```
%Error: dut.sv:2:30: CONST '32'sh0' is not an unpacked array, but is in an unpacked array context
    2 |     int a[4][4] = '{default: 0};
      |                              ^
```

The IEEE 1800-2017 SystemVerilog standard says this in section _10.9.1 Array assignment patterns_ (emphasis mine),
>The default:value applies to elements or subarrays that are not matched by either index or type
key. If the type of the element or subarray is a simple bit vector type, matches the self-determined
type of the value, or is not an array or structure type, then the value is evaluated in the context of
each assignment to an element or subarray by the default and shall be castable to the type of the
element or subarray; otherwise, an error is generated. **For unmatched subarrays, the type and default
specifiers are applied recursively according to the rules in this subclause to each of its elements or
subarrays.** For unmatched structure elements, the type and default keys are applied to the element
according to the rules for structures.

I am using `Verilator 5.015 devel rev v5.014-82-g567644313`, which is fairly recent. I don't see any release notes indicating that this has subsequently been fixed.

I note also that several commercial simulators support this.

I am interested in contributing to the Verilator project, but it will likely be some time before I can contribute productively. If I can be pointed in the right direction I may try to look at fixing this issue.

Ps. for those looking for a temporary workaround you can nest your default statements and Verilator will not throw an error (although I have not functionally tested this):
```verilog
module dut;
   int a[4][4] = '{default: '{default: 0}};
endmodule
```

### PR DESCRIPTION
**Pull request by Mo0nbase**
Fixes #2491.

## Summary
Verilator was rejecting legal unpacked-array default assignment patterns like `int a[4][4] = '{default: 0};` because it tried to assign the scalar default directly to a subarray instead of applying `default` recursively. This patch is necessary to implement IEEE 1800 recursive default behavior for unpacked subarrays so standards-compliant source (including transpiled code) no longer fails elaboration/lint.

## Issue
Fixes https://github.com/verilator/verilator/issues/4589

## Root Cause
In `WidthVisitor::patternArray` (`src/V3Width.cpp`), when an element was filled from `default: ...`, Verilator cloned the default pattern member and immediately typed it as the subelement dtype. For unpacked subarray elements, scalar defaults (for example `0`) must first be interpreted as a recursive default pattern (`'{default: 0}` at the next level), but that recursion was not synthesized, leading to unpacked-array type errors.

## Changes
- `src/V3Width.cpp`
  - Added `defaultPatp_patternArray(AstPatMember* defaultp, AstNodeDType* elemDTypep)`.
  - For unpacked subarray elements:
    - Keep existing behavior if value is already a pattern.
    - Keep existing behavior if value is directly assignable to the subarray type.
    - Otherwise rewrite the element default into a recursive pattern form equivalent to `'{default: value}`.
  - `patternArray(...)` now uses `defaultPatp_patternArray(...)` instead of raw `defaultp->cloneTree(false)`.
- Added regression test:
  - `test_regress/t/t_array_pattern_default_recursive.v`
  - `test_regress/t/t_array_pattern_default_recursive.py`

### Environment
- Command: `./bin/verilator --version`
- Result: `Verilator 5.047 devel rev v5.046-53-g4f4d48e9d (mod)`

### 1. Fixed behavior: recursive default on unpacked subarrays now accepted
- Testcase:
  ```systemverilog
  module dut;
     int a[4][4] = '{default: 0};
  endmodule
  ```
- Command: `./bin/verilator --lint-only /tmp/repro_4589_default.sv`
- Result: Pass (exit code 0)

### 2. Non-regression: direct array-typed default value still accepted
- Testcase:
  ```systemverilog
  module t;
    int row[4] = '{1,2,3,4};
    int c[2][4] = '{default: row};
  endmodule
  ```
- Command: `./bin/verilator --lint-only /tmp/repro_default_row.sv`
- Result: Pass (exit code 0)

### 3. Regression test added for this fix
- Command: `./bin/verilator --binary test_regress/t/t_array_pattern_default_recursive.v && ./obj_dir/Vt_array_pattern_default_recursive`
- Result: Pass, runtime prints `*-* All Finished *-*`

### CODE REVIEW

File: src/V3Width.cpp [hunk 1]
```diff
@@ -5282,6 +5282,30 @@ class WidthVisitor final : public VNVisitor {
...
+        if (VN_IS(valuep, Pattern)) return newpatp;
+        if (!valuep->dtypep()) userIterate(valuep, WidthVP{SELF, BOTH}.p());
+        if (valuep->dtypep()
+            && AstNode::computeCastable(valuep->dtypep()->skipRefp(), elemDTypeSkipRefp, nullptr)
+                   .isAssignable()) {
+            return newpatp;
+        }
+
+        AstNodeExpr* const recursiveValuep = valuep->unlinkFrBack();
+        VL_DO_DANGLING(pushDeletep(newpatp), newpatp);
```
Comment (wsnyder) [inline src/V3Width.cpp]: No need to create it just to delete it, up above just use `defaultp->cloneTree(false)` to replace the newpatp's.

File: test_regress/t/t_array_pattern_default_recursive.v [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+// SPDX-License-Identifier: CC0-1.0
+
+module t;
+
+  int arr_default_scalar[4][4];
+  int row[4];
+  int arr_default_array[2][4];
+
+  initial begin
+    arr_default_scalar = '{default: 0};
```
Comment (wsnyder) [inline test_regress/t/t_array_pattern_default_recursive.v:15]: Please test having different defaults in different subarrays, e.g. '{1, default: {2, default: 3}"`

**Review by wsnyder — COMMENTED** [review]
Thanks for your first pull.

**Comment by Mo0nbase** [comment]
Thanks for the quick turnaround! I addressed the comments.

**Comment by wsnyder** [comment]
Thanks. Please address the test failures (ideally running locally or on a private branch versus this one), and once passing I'll merge.

**Comment by Mo0nbase** [comment]
> Thanks. Please address the test failures (ideally running locally or on a private branch versus this one), and once passing I'll merge.

%p constant-folding only supported 1D unpacked arrays and I've altered it to reflect the correct internal structure instead of returning %@.

I also updated the golden reference, and the SPDX headers to be compliant with CI.

Thanks again!
