### PR TITLE
Fix VCD scope types

### LINKED ISSUE #4227: Fix non-standard of 'struct' in VCD traces
Verilator version: 4.110
OS: Ubuntu-20.04
I performed RTL simulation using verilator and generated a VCD of that RTL [ https://github.com/openhwgroup/cva6 ]  simulations without any error. While using that VCD in cadence tools, the tool saying there is syntax error at line 114 in VCD file.

The VCD file snapshot: 
vcd_snapshot

Can anyone help what's wrong here? 
Thanks!

### PR DESCRIPTION
**Pull request by atorregrosa-smd**
This limits the custom struct/union/interface scope types to be issued only in FST traces, since they are non-standard for VCD.

Should fix #4227

### CODE REVIEW

File: src/V3TraceDecl.cpp [hunk 1]
```diff
@@ -196,7 +196,10 @@ class TraceDeclVisitor final : public VNVisitor {
     }
 
     std::string getScopeChar(VltTraceScope sct) {
-        return std::string(1, static_cast<char>(0x80 + sct));
+        if (v3Global.opt.traceFormat().fst())
+            return std::string(1, static_cast<char>(0x80 + sct));
+        else
+            return std::string();
```
Comment (wsnyder) [inline src/V3TraceDecl.cpp:202]:
```suggestion
        if (v3Global.opt.traceFormat().fst()) {
            return std::string(1, static_cast<char>(0x80 + sct));
        } else {
            return std::string();
        }
```

**Review by wsnyder — COMMENTED** [review]
Thanks, just a minor style item if you please.
