### PR TITLE
Fix handling input file path separator (#4515)

### LINKED ISSUE #4515: Minor file path parsing bug (.//adc.v).
$ verilator --version
Verilator 5.006 2023-01-22 rev (Debian 5.006-3)
$ uname -a
Linux oldell 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux 12 \n \l

verilator --Mdir adc_obj_dir --prefix Vlng --CFLAGS -fpic --cc .//adc.v
%Error: File not found: /adc.v
%Error: Exiting due to 1 error(s)

With one '/' it is fine.  Such '//' paths may be easily created when scripting.

### PR DESCRIPTION
**Pull request by donlon**
FIx #4515 and cleanup the paths before printing them. The output may looks much better now.

Also concatenate paths using platform-specific separator, so there won't be path likes `a\path/file.sv` output to console on Windows.

### CODE REVIEW

File: src/V3EmitCFunc.h [hunk 1]
```diff
@@ -634,9 +634,9 @@ class EmitCFunc VL_NOT_FINAL : public EmitCConstInit {
             if (v3Global.opt.trace()) {
                 puts("vlSymsp->_traceDumpOpen();\n");
             } else {
-                puts("VL_PRINTF_MT(\"-Info: ");
-                puts(protect(nodep->fileline()->filename()));
-                puts(":");
+                puts("VL_PRINTF_MT(\"-Info: \"");
+                putsQuoted(protect(nodep->fileline()->filename()));
+                puts("\":");
```
Comment (wsnyder) [inline src/V3EmitCFunc.h:639]:
```suggestion
                puts("VL_PRINTF_MT(\"-Info: ");
                puts(V3OutFormatter::quoteNameControls(protect(nodep->fileline()->filename())));
                puts(":");
```

File: src/V3EmitCMake.cpp [hunk 2]
```diff
@@ -88,7 +84,8 @@ class CMakeEmitter final {
         *of << "\n### Constants...\n";
         cmake_set(*of, "PERL", V3Options::getenvPERL(), "FILEPATH",
                   "Perl executable (from $PERL)");
-        cmake_set(*of, "VERILATOR_ROOT", V3Options::getenvVERILATOR_ROOT(), "PATH",
+        cmake_set(*of, "VERILATOR_ROOT",
+                  V3OutFormatter::quoteNameControls(V3Options::getenvVERILATOR_ROOT()), "PATH",
```
Comment (wsnyder) [inline src/V3EmitCMake.cpp:88]: Ok, but then also please fix PERL immediately above, and any others.

File: src/V3EmitMk.cpp [hunk 3]
```diff
@@ -154,7 +154,8 @@ class EmitMk final {
         of.puts("# Perl executable (from $PERL)\n");
         of.puts("PERL = " + V3Options::getenvPERL() + "\n");
         of.puts("# Path to Verilator kit (from $VERILATOR_ROOT)\n");
-        of.puts("VERILATOR_ROOT = " + V3Options::getenvVERILATOR_ROOT() + "\n");
+        of.puts("VERILATOR_ROOT = "
+                + V3OutFormatter::quoteNameControls(V3Options::getenvVERILATOR_ROOT()) + "\n");
```
Comment (wsnyder) [inline src/V3EmitMk.cpp:158]: Fix PERL immediately above and any others.

File: src/V3Os.cpp [hunk 4]
```diff
@@ -392,3 +427,27 @@ int V3Os::system(const string& command) {
         return exit_code;
     }
 }
+
+void V3Os::selfTest() {
+#ifdef VL_DEBUG
+    UASSERT_SELFTEST(string, filenameCleanup(""), "");
```
Comment (wsnyder) [inline src/V3Os.cpp:433]: Thanks for adding tests for these.

File: src/V3Os.cpp [hunk 5]
```diff
@@ -124,15 +124,46 @@ void V3Os::setenvStr(const string& envvar, const string& value, const string& wh
 //######################################################################
 // Generic filename utilities
 
-static bool isSlash(char ch) VL_PURE { return ch == '/' || ch == '\\'; }
+#if defined(_WIN32) || defined(__MINGW32__)
+static const char s_slash = '\\';
+#else
+static const char s_slash = '/';
```
Comment (wsnyder) [inline src/V3Os.cpp:130]:
```suggestion
static constexpr char V3OS_SLASH = '\\';
#else
static constexpr char V3OS_SLASH = '/';
```

File: src/V3String.cpp [hunk 6]
```diff
@@ -20,6 +20,7 @@
 #include "V3String.h"
 
 #include "V3Error.h"
+#include "V3FileLine.h"
```
Comment (wsnyder) [inline src/V3String.cpp:23]: V3String is supposed to be low-level routines so I'd prefer not to have a FileLine dependence (and the related mess with VL_COVERAGE).

Choices are to move unquoteSVString perhaps to V3File to match the corresponding inverse, or have it return a error string that the caller handles.

File: src/V3String.h [hunk 7]
```diff
@@ -75,6 +75,8 @@ inline string ucfirst(const string& text) {
     return result;
 }
 
+class FileLine;
+
```
Comment (wsnyder) [inline src/V3String.h:79]: As above.

**Review by wsnyder — COMMENTED** [review]
Please merge in master as there are conflicts.

This seems a bit larger of a patch, I'd ideally like it smaller as pieces, but I can see how you got down a path and collected them all, so I suppose it's ok to take them together.

File: src/V3EmitCFunc.h (hunk 1 above)
Comment (donlon) [reply src/V3EmitCFunc.h:639]: Yes it's more efficient

File: src/V3EmitCMake.cpp (hunk 2 above)
Comment (donlon) [reply src/V3EmitCMake.cpp:88]: done

File: src/V3Os.cpp (hunk 4 above)
Comment (donlon) [reply src/V3Os.cpp:433]: You're welcome :)

File: src/V3Os.cpp (hunk 5 above)
Comment (donlon) [reply src/V3Os.cpp:130]: done

File: src/V3String.cpp (hunk 6 above)
Comment (donlon) [reply src/V3String.cpp:23]: V3File is dedicated to file IO and content generation, so still put in V3String, but return an error message instead of using FileLine

**Comment by donlon** [comment]
done
