### PR TITLE
Fix #2328: Struct data type assignment 

### LINKED ISSUE #2328: Support pattern member assignment with data type
Medium starter task that could be straight-forward or could get complicated - not sure ;)

This [sv-tests](https://github.com/SymbiFlow/sv-tests) fail:

* tests/chapter-5/5.10-structures.sv 

Because Verilator should support pattern members with data types, e.g.

    ms = '{ int:0, int:1};

To fix this, 1. add appropriate tests. 2. Comment in the verilog.y has a patternKey rule for simple_type  to make an appropriate Ast type. 3. the pattern matching rules need to look for appropriate types.

### PR DESCRIPTION
**Pull request by MG525**
1. The idea of new implementation is to only iterate over patterns and store {member: value} and {data_type: value} in different hashes then if member definitions are assigned look into data_type assignment then look into default.

2. Also latest data_type assignment is to be considered as mentioned by IEEE 1800-2017 SV 

3. Little modification is done to "Assignment pattern missed initializing elements" error where you see actual data type used 

4. Some comments are added for easier maintenance in the future

### CODE REVIEW

**Comment by MG525** [comment]
I have updated my Profile Name and "Contributor Agreement" should work now but I am not sure if I have the permission to rerun the action because could not find option for that

File: src/V3Width.cpp [hunk 1]
```diff
@@ -3413,50 +3413,68 @@ class WidthVisitor final : public VNVisitor {
...
+                        }
+                        else if (const AstNodeDType* nodedtypep = VN_CAST(patp->keyp(), NodeDType)){
+                            // data_type: default_value
+                            const string dtype = nodedtypep->dtypep()->prettyDTypeName();
+                            auto it = dtypemap.find(dtype);
+                            if (it == dtypemap.end()) {
+                                dtypemap.emplace(dtype, patp);
                             }
+                            else {
+                                //override stored default_value
```
Comment (wsnyder) [inline src/V3Width.cpp:3453]:
```suggestion
                                // Override stored default_value
```

File: src/V3Width.cpp [hunk 2]
```diff
@@ -3413,50 +3413,68 @@ class WidthVisitor final : public VNVisitor {
...
+                                it->second = patp->cloneTree(false);
+                            }
+                        }
+                        else {
+                            // undefined pattern
```
Comment (wsnyder) [inline src/V3Width.cpp:3458]:
```suggestion
                            // Undefined pattern
```

File: src/V3Width.cpp [hunk 3]
```diff
@@ -3413,50 +3413,68 @@ class WidthVisitor final : public VNVisitor {
...
-                        patp = nullptr;
-                        break;
-                    } else {
-                        const std::pair<PatMap::iterator, bool> ret = patmap.emplace(memp, patp);
-                        if (!ret.second) {
-                            patp->v3error("Assignment pattern contains duplicate entry: "
-                                          << VN_AS(patp->keyp(), Text)->text());
+                    else{
+                        // constant expr
+                        if(memp){
```
Comment (wsnyder) [inline src/V3Width.cpp:3466]:
```suggestion
                        if (memp) {
```

File: src/V3Width.cpp [hunk 4]
```diff
@@ -3467,13 +3485,24 @@ class WidthVisitor final : public VNVisitor {
             AstPatMember* newpatp = nullptr;
             AstPatMember* patp = nullptr;
             if (it == patmap.end()) {
-                if (defaultp) {
+                const string memp_DType = memp->virtRefDTypep()->prettyDTypeName();
+                const auto it2 = dtypemap.find(memp_DType);
+                if(it2 != dtypemap.end()){
```
Comment (wsnyder) [inline src/V3Width.cpp:3490]:
```suggestion
                if (it2 != dtypemap.end()) {
```

File: src/V3Width.cpp [hunk 5]
```diff
@@ -3467,13 +3485,24 @@ class WidthVisitor final : public VNVisitor {
...
+                    // default_value for data_type
+                    patp = it2->second;
+                    newpatp = patp->cloneTree(false);
+                    patp = newpatp;
+                }
+                else if (defaultp) {
+                    //default_value for any unassigned member yet
```
Comment (wsnyder) [inline src/V3Width.cpp:3497]:
```suggestion
                    // default_value for any unassigned member yet
```

**Review by wsnyder — APPROVED** [review]
Thanks for working on this.

File: src/V3Width.cpp [hunk 6]
```diff
@@ -3413,50 +3413,68 @@ class WidthVisitor final : public VNVisitor {
...
+                            else {
+                                //override stored default_value
+                                it->second = patp->cloneTree(false);
+                            }
+                        }
+                        else {
+                            // undefined pattern
+                            patp->keyp()->v3error(
+                                "Assignment pattern key not supported/understood: "
+                                << patp->keyp()->prettyTypeName());
```
[the remark this answers is not in the document]
Comment (MG525) [reply src/V3Width.cpp:3460]: Added by commit 76b4247

File: src/V3Width.cpp [hunk 7]
```diff
@@ -3413,50 +3413,68 @@ class WidthVisitor final : public VNVisitor {
...
-                        if (!ret.second) {
-                            patp->v3error("Assignment pattern contains duplicate entry: "
-                                          << VN_AS(patp->keyp(), Text)->text());
+                    else{
+                        // constant expr
+                        if(memp){
+                            const std::pair<PatMap::iterator, bool> ret = patmap.emplace(memp, patp);
+                            if (!ret.second) {
+                                patp->v3error("Assignment pattern contains duplicate entry: "
+                                                << VN_AS(patp->keyp(), Text)->text());
```
[the remark this answers is not in the document]
Comment (MG525) [reply src/V3Width.cpp:3469]: Yes this one already exists at t_struct_init_bad.pl

File: src/V3Width.cpp [hunk 8]
```diff
@@ -3413,50 +3413,68 @@ class WidthVisitor final : public VNVisitor {
         // which member each AstPatMember corresponds to before we can
         // determine the dtypep for that PatMember's value, and then
         // width the initial value appropriately.
-        using PatMap = std::map<const AstMemberDType*, AstPatMember*>;
+        using PatMap = std::map<const AstMemberDType*, AstPatMember*>; //store member: value
+        using DTypeMap = std::map<const std::string, AstPatMember*>; // store data_type: default_value
```
[the remark this answers is not in the document]
Comment (MG525) [reply src/V3Width.cpp]: Yes I have tried to check another identifier but could not find a suitable one other than this. Just let me know if you have any other suggestion even in the future

File: src/V3Width.cpp [hunk 9]
```diff
@@ -3413,50 +3413,67 @@ class WidthVisitor final : public VNVisitor {
         // which member each AstPatMember corresponds to before we can
         // determine the dtypep for that PatMember's value, and then
         // width the initial value appropriately.
-        using PatMap = std::map<const AstMemberDType*, AstPatMember*>;
+        using PatMap = std::map<const AstMemberDType*, AstPatMember*>; // Store member: value
+        using DTypeMap = std::map<const std::string, AstPatMember*>; // Store data_type: default_value
```
Comment (wsnyder) [inline src/V3Width.cpp:3417]:
```suggestion
        using PatMap = std::map<const AstMemberDType*, AstPatMember*>;  // Store member: value
        using DTypeMap = std::map<const std::string, AstPatMember*>;  // Store data_type: default_value
```

Still not sure why the autoformatter didn't fix this for you...  I see the action did run.

Comment (MG525) [reply src/V3Width.cpp:3417]: Sorry but when this auto formatter should work? Or in which part should this be checked?
