### PR TITLE
Fix AstStructSel clean when data type is structure (#4241)

### LINKED ISSUE #4241: Unpacked structure faulty comparison of sub structure
Continuation of #4240 , but different issue.

```systemverilog
module t;
    typedef struct {
        struct {
            logic m0;
            logic [3:0] m1;
            logic m2;
        } sub;
    } struct_t;
    struct_t s1;
    struct_t s2;

    assign {s1.sub.m0, s1.sub.m1, s1.sub.m2} = {1'b0, 4'h5, 1'b1};
    assign {s2.sub.m0, s2.sub.m1, s2.sub.m2} = {1'b0, 4'h5, 1'b1};
    
    initial begin
        if(s1.sub != s2.sub) begin
            $fatal();
        end else begin
            $finish();
        end
    end

endmodule
```

Results in:
`verilator_bin  --build --main --binary --cc  test2.sv`

```
Vtest2___024root__DepSet_hef21559d__0__Slow.cpp: In function ‘void Vtest2___024root___eval_initial__TOP(Vtest2___024root*)’:
Vtest2___024root__DepSet_hef21559d__0__Slow.cpp:22:26: error: no match for ‘operator&’ (operand types are ‘unsigned int’ and ‘Vtest2___struct4’)
   22 |     if (VL_UNLIKELY(((1U & vlSelf->t__DOT__s1.__PVT__sub)
      |                       ~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       |                       |
      |                       unsigned int            Vtest2___struct4
/tools/work/SoCMake-Ibex/deps/_deps/verisc/open/verilator-106965270/share/verilator/include/verilatedos.h:66:45: note: in definition of macro ‘VL_UNLIKELY’
   66 | # define VL_UNLIKELY(x) __builtin_expect(!!(x), 0)  // Prefer over C++20 [[unlikely]]
      |                                             ^
Vtest2___024root__DepSet_hef21559d__0__Slow.cpp:23:29: error: no match for ‘operator&’ (operand types are ‘unsigned int’ and ‘Vtest2___struct4’)
   23 |                      != (1U & vlSelf->t__DOT__s2.__PVT__sub)))) {
      |                          ~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |                       |
      |                          unsigned int            Vtest2___struct4
/tools/work/SoCMake-Ibex/deps/_deps/verisc/open/verilator-106965270/share/verilator/include/verilatedos.h:66:45: note: in definition of macro ‘VL_UNLIKELY’
```

The error is in 1U & struct, this bitwise should be removed in case of structure comparison.
I am not sure why is it there in the first place?

I can proceed to remove the bitwise & for the case of struct if that is what needs to be done?

### PR DESCRIPTION
**Pull request by Risto97**
This should fix #4241 
Depends on #4234 , because I reused the test.
I can create a new test if needed.

### CODE REVIEW

File: src/V3Clean.cpp [hunk 1]
```diff
@@ -234,6 +234,13 @@ class CleanVisitor final : public VNVisitor {
         operandTriop(nodep);
         setClean(nodep, nodep->cleanOut());
     }
+    void visit(AstStructSel* nodep) override {
+        iterateChildren(nodep);
+        if (VN_CAST(nodep->dtypep(), StructDType))
+            setClean(nodep, true);
+        else
+            setClean(nodep, false);
```
Comment (wsnyder) [inline src/V3Clean.cpp:242]:
```suggestion
        AstStructDTypep* dtypep = VN_CAST(nodep->dtypep()->skipRefp(), StructDType);
        setClean(nodep, dtypep && dtypep->isPacked());
```

File: src/V3Clean.cpp [hunk 2]
```diff
@@ -234,6 +234,14 @@ class CleanVisitor final : public VNVisitor {
         operandTriop(nodep);
         setClean(nodep, nodep->cleanOut());
     }
+    void visit(AstStructSel* nodep) override {
+        iterateChildren(nodep);
+        AstStructDType* dtypep = VN_CAST(nodep->dtypep()->skipRefp(), StructDType);
+        if(dtypep)
+            setClean(nodep, !dtypep->packed());
+        else
+            setClean(nodep, false);
```
Comment (wsnyder) [inline src/V3Clean.cpp:243]:
```suggestion
        setClean(nodep, dtypep && !dtypep->packed());
```
