### PR TITLE
 Fix #3445 of BitOpTreeOpt

### LINKED ISSUE #3445: V3Const BitOpTree optimization is incorrect
I've got 2 designs that trigger bug with BitOpTree optimization in V3Const.
[test.zip](https://github.com/verilator/verilator/files/8772881/test.zip)
They are called `pack_struct_bug` and `pack_struct_2bug`.

Both of this designs use array of structs.
There is also `pack_struct_different_order` design that uses packed struct, but order of fields is different and bug is not triggered.
`verilator --version : Verilator 4.223 devel rev v4.222-11-gf6035447`

I'm running Debian Linux docker container for testing.

Main issue here is that `ConstBitOpTreeVisitor` visitor going down expresion tree does not keep tract of previous nodes it had seen.
Path like `AstAnd -> AstShiftR -> AstAnd -> AstArraySel` created fail as AstArraySel is not handled. This would make `AstArraySel` subtree as frozen node and information of `AstShiftR` before `AstArraySel` would be lost. This is a case in `pack_struct_bug`.
In `pack_starct_2bug`path is `AstAnd -> AstNot -> AstShiftR -> AstAnd -> AstArraySel`. In this case both `AstNot` and `AstShiftR` nodes are lost.

I don't know best solution to this issue but I've came up with a fix. 
It is rather crude as it may disable optimization in some cases that it's not needed.
[BiOpFix.txt](https://github.com/verilator/verilator/files/8773009/BiOpFix.txt)

[edit]
I've tested how this affects speed of simulation. The way it's right now, simulation was 3 times slower.

### PR DESCRIPTION
**Pull request by yTakatsukasa**
second shot of #3452 

As written in https://github.com/verilator/verilator/issues/3445#issue-1248381686, LSB of frozen node has been ignored. This PR keeps the information and insert AstShiftR if LSB > 0.

As usual, I will push test first to see the CI failure, then push the fix.

### CODE REVIEW

**Comment by yTakatsukasa** [comment]
7d3a3ba628fff0e84cdee33f4df7615658305b19 fails as expected, then 77e4eb3a5cf687d101254a4438d21d65df59a386 fixes the test.

File: src/V3Const.cpp [hunk 1]
```diff
@@ -681,7 +690,8 @@ class ConstBitOpTreeVisitor final : public VNVisitor {
         if (debug() >= 9) {  // LCOV_EXCL_START
             cout << "Bitop tree considered: " << endl;
             for (AstNode* const termp : termps) termp->dumpTree("Reduced term: ");
-            for (AstNode* const termp : visitor.m_frozenNodes) termp->dumpTree("Frozen term: ");
+            for (const std::pair<AstNode*, int>& termp : visitor.m_frozenNodes)
+                termp.first->dumpTree("Frozen term lsb:" + std::to_string(termp.second) + " :");
```
Comment (gezalore) [inline src/V3Const.cpp:694]:
```suggestion
                termp.first->dumpTree("Frozen term with lsb " + std::to_string(termp.second) + ": ");
```

File: src/V3Const.cpp [hunk 2]
```diff
@@ -672,7 +677,11 @@ class ConstBitOpTreeVisitor final : public VNVisitor {
         const bool needsCleaning = visitor.isAndTree() ? !hasCleanTerm : hasDirtyTerm;
 
         // Add size of reduction tree to op count
-        resultOps += termps.size() + visitor.m_frozenNodes.size() - 1;
+        resultOps += termps.size() - 1;
+        for (auto&& lsbAndNodes : frozenNodes) {
```
Comment (gezalore) [inline src/V3Const.cpp:681]:
```suggestion
        for (const auto& lsbAndNodes : frozenNodes) {
```

File: test_regress/t/t_const_opt.v [hunk 3]
```diff
@@ -140,3 +144,38 @@ module bug3197(input wire clk, input wire [31:0] in, output out);
    wire tmp0 = (|d[38:0]);
    assign out = (d[39] | tmp0);
 endmodule
+
+module bug3445(input wire clk, input wire [31:0] in, output wire out);
```
Comment (gezalore) [inline test_regress/t/t_const_opt.v:148]: Please add a comment explaining what this is testing as it is non-obvious from the code.

File: src/V3Const.cpp [hunk 4]
```diff
@@ -724,8 +734,19 @@ class ConstBitOpTreeVisitor final : public VNVisitor {
             resultp = reduce(resultp, termp);
         }
         // Add any frozen terms to the reduction
-        for (AstNode* const frozenp : visitor.m_frozenNodes) {
-            resultp = reduce(resultp, frozenp->unlinkFrBack());
+        for (auto&& lsbAndNodes : frozenNodes) {
+            AstNode* termp = lsbAndNodes.second.front()->unlinkFrBack();
+            for (size_t i = 1; i < lsbAndNodes.second.size(); ++i) {
+                termp = reduce(termp, lsbAndNodes.second[i]->unlinkFrBack());
+            }
```
Comment (gezalore) [inline src/V3Const.cpp:741]:
```suggestion
            AstNode* termp = nullptr;
            for (AstNode* const itemp : lsbAndNodes.second) {
                termp = reduce(termp, itemp->unlinkFrBack());
            }
```

**Review by gezalore — COMMENTED** [review]
Makes sense, thanks for tracking it down and the fix! Please merge when you are happy.

**Comment by yTakatsukasa** [comment]
Thanks for the review.
I will merge when CI passes.

verilator_ext tests pass, btw.
