### PR TITLE
Fix support disable task by name (#6853)

### LINKED ISSUE #6853: Support disabling task by name
Currently UVM tests/40phasing/50phase_controls/00basic fails with 

`%Error-UNSUPPORTED: file.v:37:10: Unsupported: disabling task by name`

From doing roughly this:

```
class driver;
     task get_and_send();
       forever begin
         ...
       end
     endtask
     task post_shutdown_phase(uvm_phase phase);
       disable get_and_send;  // <---
```

The existing test case for this error will be extended for this case shortly.

Related-ish to #5432

### PR DESCRIPTION
**Pull request by nbstrike**
Adds support for disable <task_name> (including dotted task scope resolution cases already covered by regressions, fixes #6853) and fixes a related runtime issue where killing a forked task process could leave fork..join blocked due to miscounting completed tasks. Adds in a number of regression test cases to exercise the change.

As a note I did tackle this with genai (which seems to be allowed).

### CODE REVIEW

File: src/V3Timing.cpp [hunk 1]
```diff
@@ -742,6 +742,24 @@ class TimingControlVisitor final : public VNVisitor {
         addDebugInfo(donep);
         beginp->addStmtsp(donep->makeStmt());
     }
+    // Register a callback so killing a process-backed fork branch decrements the join counter
+    void addForkOnKill(AstBegin* const beginp, AstVarScope* const forkVscp) const {
+        if (!beginp->needProcess()) return;
+        FileLine* const flp = beginp->fileline();
+        auto* const onKillp = new AstCMethodHard{flp, new AstVarRef{flp, forkVscp, VAccess::WRITE},
```
Comment (wsnyder) [inline src/V3Timing.cpp]:
```suggestion
        AstCMethodHard* const onKillp = new AstCMethodHard{flp, new AstVarRef{flp, forkVscp, VAccess::WRITE},
```

File: include/verilated_timing.h [hunk 2]
```diff
@@ -383,40 +383,59 @@ struct VlForever final {
...
-    struct VlJoin final {
-        size_t m_counter = 0;  // When reaches 0, resume suspended coroutine
-        VlCoroutineHandle m_susp;  // Coroutine to resume
-    };
+// Shared fork..join state, because VlForkSync is copied into generated coroutine frames.
+class VlForkSyncState final {
+public:
+    size_t m_counter = 0;  // When reaches 0, resume suspended coroutine
+    VlCoroutineHandle m_susp;  // Coroutine to resume
+    bool m_inited = false;
```
Comment (wsnyder) [inline include/verilated_timing.h:391]: Comment, even though trivial.

**Comment by nbstrike** [comment]
> Running UVM tests/40phasing/50phase_controls/00basic
> 
> %Error: Internal Error: test.sv:66:5: ../V3LinkJump.cpp:420: Unlinked disable statement 66 | disable get_and_send;
> 
> ```
> class basic_driver extends uvm_driver #(basic_item);
> ...
>   task get_and_send();
>     forever begin
>       #10;
>       ...
>     end
>   endtask
>   task run_phase (uvm_phase phase);
>     get_and_send();
>   endtask
>   task post_shutdown_phase(uvm_phase phase);
>     //Should stop accepting and sending request here.
>     disable get_and_send;
>   endtask
> endclass
> ```

I've been trying to reproduce this error, but I don't seem to be having much luck so I'm not too sure what I'm doing wrong here (I'm also not too familiar with the uvm-tests, which might be another factor).

I cloned the repo at https://github.com/accellera/uvm.git, ran verilator like:
```
verilator --binary --timing --comp-limit-members 10 --top-module top -j 0 -Wno-fatal -Wno-DEFOVERRIDE -Mdir /tmp/obj_uvm_00basic --prefix Vuvm_00basic_recheck +define+UVM_NO_DPI +define+UVM_REGEX_NO_DPI +define+VCS +incdir+distrib/src +incdir+tests/40phasing/50phase_controls/00basic +incdir+tests/40phasing/50phase_controls/common distrib/src/uvm_pkg.sv tests/40phasing/50phase_controls/00basic/test.sv
```

Which succeeded, and the resulting binary runs to completion, with a "** UVM TEST PASSED **" message.

I wonder what I could be doing wrong here, the message you have is the same as I get without this change albeit on a different line number so perhaps I'm looking at a different test version?

**Comment by wsnyder** [comment]
My mistake, I was running against master, that test does work with your changes.

I'll merge this after the release.

**Comment by wsnyder** [comment]
This pull fails uvm_test tests/40phasing/90Mantis/3622hang_the_sequencer_item

Also, when combined with #7141 it fails uvm_test tests/70regs/90Mantis/3860_reg_bus_coupling
which might be this pull's fault, #7141's, or some new mix of behavior.

**Comment by nbstrike** [comment]
> This pull fails uvm_test tests/40phasing/90Mantis/3622hang_the_sequencer_item

What output do you get, I'm unable to reproduce locally from uvm-1.2 with this branch (or after merging in master at 2ceea267e).

**Comment by wsnyder** [comment]
Please email wsnyder@wsnyder.org with your email address and I'll send the test.

**Comment by wsnyder** [comment]
The iverilog always3.1.9C test now compiles with this, but hangs.  If this is due to a different bug it's ok to ignore it.
Also there's a bunch of ivtests that still fail with disabled errors, which is ok if your intent, but please check through them.

```
regress-sv_clkgen_bit_iv
regress-sv_clkgen_logic_iv
regress-sv_clkgen_net_iv
regress-sv_clkgen_reg_iv
regress-sv_fork_join_dis_iv
regress-vlg_always319D_iv
regress-vlg_disable36A_iv
regress-vlg_disable_cleanup_iv
regress-vlg_pr540_iv
regress-vlg_pr540b_iv
regress-vlg_pr540c_iv
regress-vlg_pr987_iv
regress-vlg_sdw_dsbl_iv
```

```
module main ;
reg [3:0] value1 ;

task foo ;
  value1 = #2  1;
endtask

initial
  begin
    value1 = 1'b0;
    #5;
    foo ;
    #4 ;
    if(value1 === 1'b0)
      $display("PASSED");
    else
      $display("FAILED - always3.1.9C always #2 disable foo");
    $finish ;
  end

always #6 disable foo ;

endmodule
```

**Comment by nbstrike** [comment]
> The iverilog always3.1.9C test now compiles with this, but hangs. If this is due to a different bug it's ok to ignore it. Also there's a bunch of ivtests that still fail with disabled errors, which is ok if your intent, but please check through them.

I've fixed the example you pasted -- the cause was trying to kill the invoking process -- but haven't had time yet to run through all of the ivtests.

The fix has been to wrap all tasks which can be disabled in a fork..join construct so that they get a distinct process.

**Comment by nbstrike** [comment]
> This pull fails uvm_test tests/40phasing/90Mantis/3622hang_the_sequencer_item

If this is still an issue I'll email & can look into it.

**Comment by wsnyder** [comment]
Unfortunately tests/40phasing/90Mantis/3622hang_the_sequencer_item  fails with this.  Email me if you need an example.

**Comment by nbstrike** [comment]
> Unfortunately tests/40phasing/90Mantis/3622hang_the_sequencer_item fails with this. Email me if you need an example.

I tested and saw a failure with the branch as is, this seems to be resolved by #6933 so merging in master now verilates for me, and runs albeit failing with a UVM report.

**Comment by wsnyder** [comment]
Agreed, passes now.
