### PR TITLE
Fix inside operator crash with impure expression and unsized range literals (#7063)

### LINKED ISSUE #7063: Fix inside operator crash with impure expression and unsized range literals
## Summary

Verilator crashes with `Internal Error: V3Width.cpp: How can LHS be unsized?` when the `inside` operator is used with an impure LHS expression (e.g., associative array element access) and unsized integer range literals. Per IEEE 1800-2017 §11.4.13, `inside` with any expression as LHS should be supported.

## Current Behavior

- `arr[k] inside {[10:50]}` where `arr` is an associative array → internal error crash
- `impure_func() inside {[10:50]}` → same crash
- Using sized literals (`arr[k] inside {[8'd10:8'd50]}`) works around the issue

%Error: Internal Error: V3Width.cpp:5740: How can LHS be unsized?

## Expected Behavior

- `inside` with associative array element access and unsized range literals should compile and simulate correctly
- `inside` with any impure expression and unsized range literals should work

## Source

- planvtech/PlanV_Verilator_Feature_Tests#37

---
PR is coming.

### PR DESCRIPTION
**Pull request by YilouWang**
## Summary
Fix an internal error (`How can LHS be unsized?`) in `V3Width.cpp` when
the `inside` operator is used with an impure expression (e.g. associative
array element access) and unsized integer range literals.

## Issue
Fixes #7063 

## Changes
- `src/V3Width.cpp` (`visit(AstInside*)`): When creating an XTEMP variable
  to purify an impure `inside` expression, ensure the dtype is sized. The
  expression dtype may become unsized (width != widthMin) after
  context-determined extension from unsized range items like `[10:50]`.
  Use `findLogicDType`/`findBitDType` with width == widthMin to create a
  properly sized type for the temp variable.

## Test
- Added `test_regress/t/t_inside_impure_unsized.{v,py}` — tests `inside`
  with associative array elements (string key, int key) and impure function
  calls, all with unsized range literals.

---
Written by Claude Code and PlanV GmbH.

Reviewed by YilouWang.

### CODE REVIEW

File: src/V3Width.cpp [hunk 1]
```diff
@@ -3159,8 +3159,15 @@ class WidthVisitor final : public VNVisitor {
...
             FileLine* const fl = nodep->exprp()->fileline();
-            AstVar* const varp = new AstVar{fl, VVarType::XTEMP, m_insideTempNames.get(nodep),
-                                            nodep->exprp()->dtypep()};
+            // Ensure sized dtype for temp variable
+            AstNodeDType* const exprDtp = nodep->exprp()->dtypep();
+            const int w = exprDtp->width();
+            AstNodeDType* const tempDTypep = exprDtp->widthSized() ? exprDtp
+                                             : exprDtp->isFourstate()
+                                                 ? nodep->findLogicDType(w, w, exprDtp->numeric())
+                                                 : nodep->findBitDType(w, w, exprDtp->numeric());
```
Comment (wsnyder) [inline src/V3Width.cpp]: Please make a common function, and also fix the other places in V3Width to call it.
